--[[
    Project Ordinance
    Copyright (c) 2025-2026 Project Ordinance Contributors

    This file is part of Project Ordinance and is licensed under the MIT License.
    You may use, copy, modify, merge, publish, distribute, and sublicense this file
    under the terms of the LICENSE file included with this project.

    Attribution is required. If you use or modify this file, you must retain this notice.
]]

ax.localization:Register("en", {
    ["category.audio"] = "Audio",
    ["subcategory.scapes"] = "Scapes",

    ["option.scapes.enabled"] = "Enable Scapes",
    ["option.scapes.enabled.help"] = "Enable or disable all Scapes playback on your client.",
    ["option.scapes.master_volume"] = "Master Volume",
    ["option.scapes.master_volume.help"] = "Master volume multiplier for all Scapes audio.",
    ["option.scapes.loop_volume"] = "Loop Volume",
    ["option.scapes.loop_volume.help"] = "Volume multiplier for continuous loop layers.",
    ["option.scapes.random_volume"] = "Random Event Volume",
    ["option.scapes.random_volume.help"] = "Volume multiplier for randomized one-shot layers.",
    ["option.scapes.stinger_volume"] = "Stinger Volume",
    ["option.scapes.stinger_volume.help"] = "Volume multiplier for triggered stingers.",
    ["option.scapes.ambient_volume"] = "Ambient Mode Volume",
    ["option.scapes.ambient_volume.help"] = "Volume multiplier for non-positional Scapes sounds.",
    ["option.scapes.positional_volume"] = "Positional Mode Volume",
    ["option.scapes.positional_volume.help"] = "Volume multiplier for positional, relative, and entity-based Scapes sounds.",
    ["option.scapes.loop_drift_scale"] = "Loop Drift Intensity",
    ["option.scapes.loop_drift_scale.help"] = "Scales subtle loop pitch/volume drift intensity.",
    ["option.scapes.pause_legacy_music"] = "Pause Legacy Ambient Music",
    ["option.scapes.pause_legacy_music.help"] = "Allow Scapes to pause legacy ambient music when requested by the active scape.",
    ["option.scapes.occlusion_enabled"] = "Sound Occlusion",
    ["option.scapes.occlusion_enabled.help"] = "Reduce positional Scapes volume when the sound is behind walls or other solid surfaces.",
    ["option.scapes.occlusion_strength"] = "Occlusion Strength",
    ["option.scapes.occlusion_strength.help"] = "Scales how strongly wall thickness muffles positional Scapes sounds on your client.",
    ["option.scapes.debug_overlay"] = "Debug Overlay",
    ["option.scapes.debug_overlay.help"] = "Show the Scapes debug overlay while enabled.",
    ["option.scapes.debug_events"] = "Debug Event Rows",
    ["option.scapes.debug_events.help"] = "How many queued events are shown in the Scapes debug overlay.",

    ["config.audio.scapes.enabled"] = "Enable Scapes",
    ["config.audio.scapes.enabled.help"] = "Enable the Scapes ambience system.",
    ["config.audio.scapes.pause_legacy_music"] = "Pause Legacy Ambient (Default)",
    ["config.audio.scapes.pause_legacy_music.help"] = "Fallback behavior for pausing legacy ambient music when a scape does not override it.",
    ["config.audio.scapes.dsp_enabled"] = "Enable DSP Support",
    ["config.audio.scapes.dsp_enabled.help"] = "Enable DSP preset application for active Scapes sessions.",
    ["config.audio.scapes.dsp_default"] = "Default DSP Preset",
    ["config.audio.scapes.dsp_default.help"] = "Default DSP preset restored when a Scapes session ends.",
    ["config.audio.scapes.dsp_default_fast_reset"] = "Default DSP Fast Reset",
    ["config.audio.scapes.dsp_default_fast_reset.help"] = "Use fast reset behavior when restoring default DSP after Scapes deactivation.",
    ["config.audio.scapes.occlusion_enabled"] = "Enable Sound Occlusion",
    ["config.audio.scapes.occlusion_enabled.help"] = "Enable wall-thickness based volume attenuation for positional Scapes sounds.",
    ["config.audio.scapes.occlusion_thickness_scale"] = "Occlusion Thickness Scale",
    ["config.audio.scapes.occlusion_thickness_scale.help"] = "Approximate wall thickness in Hammer units required to reach maximum Scapes occlusion loss.",
    ["config.audio.scapes.occlusion_max_volume_loss"] = "Occlusion Max Volume Loss",
    ["config.audio.scapes.occlusion_max_volume_loss.help"] = "Maximum volume reduction applied by Scapes wall occlusion.",
    ["config.audio.scapes.use_priority"] = "Use Scape Priority",
    ["config.audio.scapes.use_priority.help"] = "Enable priority checks when activating scapes. When disabled, newest activation always replaces the current one.",
    ["config.audio.scapes.schedule_window"] = "Schedule Window",
    ["config.audio.scapes.schedule_window.help"] = "How many seconds ahead the server schedules random events.",
    ["config.audio.scapes.schedule_refill_interval"] = "Schedule Refill Interval",
    ["config.audio.scapes.schedule_refill_interval.help"] = "How often the server checks whether schedule data should be refilled.",
    ["config.audio.scapes.schedule_refill_threshold"] = "Schedule Refill Threshold",
    ["config.audio.scapes.schedule_refill_threshold.help"] = "When remaining scheduled time falls below this threshold, more events are generated.",
    ["config.audio.scapes.batch_events"] = "Schedule Batch Size",
    ["config.audio.scapes.batch_events.help"] = "Maximum number of random events sent in one incremental schedule payload.",
    ["config.audio.scapes.net_lead_time"] = "Network Lead Time",
    ["config.audio.scapes.net_lead_time.help"] = "Lead time in seconds added before server-authored events are due on clients.",
    ["config.audio.scapes.auto_trigger_from_map"] = "Auto Trigger From Map",
    ["config.audio.scapes.auto_trigger_from_map.help"] = "Automatically trigger scapes from original env_soundscape locations parsed via NikNaks.",
    ["config.audio.scapes.auto_trigger_interval"] = "Auto Trigger Interval",
    ["config.audio.scapes.auto_trigger_interval.help"] = "How often the server reevaluates player position for map soundscape auto-triggering.",
    ["config.audio.scapes.auto_trigger_hysteresis"] = "Auto Trigger Hysteresis",
    ["config.audio.scapes.auto_trigger_hysteresis.help"] = "Stickiness threshold to avoid rapid switching between overlapping soundscape radii.",
    ["config.audio.scapes.auto_trigger_sticky_fallback"] = "Auto Trigger Sticky Fallback",
    ["config.audio.scapes.auto_trigger_sticky_fallback.help"] = "Keep the last auto-triggered scape active after leaving all parsed soundscape radii.",
    ["config.audio.scapes.auto_trigger_exit_delay"] = "Auto Trigger Exit Delay",
    ["config.audio.scapes.auto_trigger_exit_delay.help"] = "Delay before deactivating an auto-triggered scape after leaving all soundscape radii.",
    ["config.audio.scapes.auto_trigger_debug"] = "Auto Trigger Debug",
    ["config.audio.scapes.auto_trigger_debug.help"] = "Log map soundscape parser and auto-trigger diagnostics to the server console.",
    ["config.audio.scapes.debug_logging"] = "Debug Logging",
    ["config.audio.scapes.debug_logging.help"] = "Enable verbose Scapes runtime debug logging on the server.",
    ["config.audio.scapes.debug_overlay"] = "Debug Overlay (Server)",
    ["config.audio.scapes.debug_overlay.help"] = "Draw Scapes runtime debug overlays on the server.",
    ["config.audio.scapes.debug_overlay_duration"] = "Debug Overlay Duration",
    ["config.audio.scapes.debug_overlay_duration.help"] = "Server debug overlay lifetime for Scapes diagnostics.",
    ["config.audio.scapes.default_fade_in"] = "Default Fade In",
    ["config.audio.scapes.default_fade_in.help"] = "Default fade-in for scapes that do not explicitly define one.",
    ["config.audio.scapes.default_fade_out"] = "Default Fade Out",
    ["config.audio.scapes.default_fade_out.help"] = "Default fade-out for scapes that do not explicitly define one.",
})
