-- Auto-generated by tools/generate_scapes_from_soundscapes.py
-- Source: C:/Program Files (x86)/Steam/steamapps/common/GarrysMod/garrysmod/addons/rp_black_mesa_facility/scripts/soundscapes_bs_c1.txt
-- Scapes emitted: 66


ax.scapes:Register("ins.util.industrial", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:AddRandom("legacy_random_1", {
        sounds = {
            "bms_ambience/soundscape/ind_amb1.wav",
            "bms_ambience/soundscape/ind_amb2.wav",
            "bms_ambience/soundscape/ind_amb3.wav",
            "bms_ambience/soundscape/ind_amb4.wav",
            "bms_ambience/soundscape/ind_amb5.wav",
            "bms_ambience/soundscape/ind_amb6.wav",
            "bms_ambience/soundscape/ind_amb7.wav",
            "bms_ambience/soundscape/ind_amb8.wav",
            "bms_objects/elevators/elevator4_ring.wav",
        },
        volume = {0.4, 0.6},
        pitch = {90.0, 110.0},
        interval = {10.0, 15.0},
        spatial = { mode = "relative", radius = {256, 768}, hemisphere = true, soundLevel = 140 },
        limit = { instance = 1, blockDistance = 512 },
    })
end)

ax.scapes:Register("ins.util.shaftFX", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:AddRandom("legacy_random_1", {
        sounds = {
            "bms_ambience/soundscape/misc_amb1.wav",
            "bms_ambience/soundscape/misc_amb2.wav",
            "bms_ambience/soundscape/misc_amb3.wav",
            "bms_ambience/soundscape/misc_amb4.wav",
            "bms_ambience/soundscape/misc_amb5.wav",
            "bms_ambience/soundscape/misc_amb6.wav",
            "bms_ambience/soundscape/misc_amb7.wav",
            "bms_ambience/soundscape/misc_amb8.wav",
        },
        volume = {0.3, 0.5},
        pitch = {90.0, 110.0},
        interval = {15.0, 30.0},
        spatial = { mode = "relative", radius = {256, 768}, hemisphere = true, soundLevel = 120 },
        limit = { instance = 1, blockDistance = 512 },
    })
end)

ax.scapes:Register("ins.util.office", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:AddRandom("legacy_random_1", {
        sounds = {
            "bshift/bs_soundscape/soundscape_office_oneshot1.wav",
            "bshift/bs_soundscape/soundscape_office_oneshot2.wav",
            "bshift/bs_soundscape/soundscape_office_oneshot3.wav",
            "bshift/bs_soundscape/soundscape_office_oneshot4.wav",
            "bshift/bs_soundscape/soundscape_office_oneshot5.wav",
            "bshift/bs_soundscape/soundscape_office_oneshot6.wav",
            "bshift/bs_soundscape/soundscape_office_oneshot7.wav",
            "bshift/bs_soundscape/soundscape_office_oneshot8.wav",
            "bshift/bs_soundscape/soundscape_office_oneshot9.wav",
            "bshift/bs_soundscape/soundscape_office_oneshot10.wav",
            "bshift/bs_soundscape/soundscape_office_oneshot11.wav",
        },
        volume = {0.2, 0.5},
        pitch = {95.0, 105.0},
        interval = {15.0, 20.0},
        spatial = { mode = "relative", radius = {256, 768}, hemisphere = true, soundLevel = 90 },
        limit = { instance = 1, blockDistance = 512 },
    })
end)

ax.scapes:Register("insec_area3_checkpoint.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:AddLoop("r_ambience_small3", {
        sounds = "bms_ambience/room_ambience/r_ambience_small3.wav",
        volume = 0.8,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 120 },
        preload = true,
    })
    builder:AddLoop("r_ambience_lab2", {
        sounds = "bms_ambience/room_ambience/r_ambience_lab2.wav",
        volume = 1.0,
        pitch = 90.0,
        spatial = { mode = "ambient", soundLevel = 100 },
        preload = true,
    })
end)

ax.scapes:Register("insec_area3_mainhall.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:AddLoop("r_ambience_small2", {
        sounds = "bms_ambience/room_ambience/r_ambience_small2.wav",
        volume = 0.8,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 120 },
        preload = true,
    })
    builder:AddLoop("r_ambience_lab1", {
        sounds = "bms_ambience/room_ambience/r_ambience_lab1.wav",
        volume = 0.3,
        pitch = 90.0,
        spatial = { mode = "ambient", soundLevel = 100 },
        preload = true,
    })
end)

ax.scapes:Register("insec_area3_lobby.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:AddLoop("r_ambience_med6", {
        sounds = "bms_ambience/room_ambience/r_ambience_med6.wav",
        volume = 0.5,
        pitch = 110.0,
        spatial = { mode = "ambient", soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("r_ambience_lab1a", {
        sounds = "bms_ambience/room_ambience/r_ambience_lab1a.wav",
        volume = 0.3,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("r_ambience_ppl2", {
        sounds = "bms_ambience/room_ambience/r_ambience_ppl2.wav",
        volume = 0.3,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 70 },
        preload = true,
    })
end)

ax.scapes:Register("insec_area3_lockers.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:AddLoop("r_ambience_small3", {
        sounds = "bms_ambience/room_ambience/r_ambience_small3.wav",
        volume = 1.0,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 80 },
        preload = true,
    })
    builder:AddLoop("r_ambience_lab2", {
        sounds = "bms_ambience/room_ambience/r_ambience_lab2.wav",
        volume = 0.4,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 80 },
        preload = true,
    })
end)

ax.scapes:Register("insec_area3_sidehall.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:AddLoop("r_ambience_small1", {
        sounds = "bms_ambience/room_ambience/r_ambience_small1.wav",
        volume = 1.0,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 120 },
        preload = true,
    })
    builder:AddLoop("r_ambience_lab1", {
        sounds = "bms_ambience/room_ambience/r_ambience_lab1.wav",
        volume = 0.2,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 120 },
        preload = true,
    })
end)

ax.scapes:Register("insec_area3_upperhall.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:AddLoop("r_ambience_ppl1", {
        sounds = "bms_ambience/room_ambience/r_ambience_ppl1.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 110 },
        preload = true,
    })
    builder:AddLoop("r_ambience_lab1", {
        sounds = "bms_ambience/room_ambience/r_ambience_lab1.wav",
        volume = 0.3,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 100 },
        preload = true,
    })
end)

ax.scapes:Register("insec_area3_stairwell.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:AddLoop("r_ambience_med12", {
        sounds = "bms_ambience/room_ambience/r_ambience_med12.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("insec_area3_checkpoint", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:1")
    builder:AddSubScape("insec_area3_checkpoint.base")
    builder:AddLoop("m_ambience_vent2_pos0", {
        sounds = "bms_ambience/machine_ambience/m_ambience_vent2.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 60 },
        preload = true,
    })
    builder:AddLoop("m_ambience_vent1_pos1", {
        sounds = "bms_ambience/machine_ambience/m_ambience_vent1.wav",
        volume = 0.4,
        pitch = 90.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 65 },
        preload = true,
    })
    builder:AddLoop("m_ambience_vent1a_pos2", {
        sounds = "bms_ambience/machine_ambience/m_ambience_vent1a.wav",
        volume = 0.7,
        pitch = 90.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("r_ambience_med12_pos3", {
        sounds = "bms_ambience/room_ambience/r_ambience_med12.wav",
        volume = 0.4,
        pitch = 110.0,
        spatial = { mode = "positional", positionKey = 3, soundLevel = 100 },
        preload = true,
    })
end)

ax.scapes:Register("insec_area3_mainhall", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:1")
    builder:AddSubScape("insec_area3_mainhall.base")
    builder:AddSubScape("insec_area3_checkpoint.base")
    builder:AddSubScape("insec_area3_stairwell.base")
    builder:AddSubScape("ins.util.office", {
        volumeMultiplier = 0.2,
    })
    builder:AddLoop("m_ambience_vent2_pos0", {
        sounds = "bms_ambience/machine_ambience/m_ambience_vent2.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 60 },
        preload = true,
    })
    builder:AddLoop("m_ambience_vent2a_pos1", {
        sounds = "bms_ambience/machine_ambience/m_ambience_vent2a.wav",
        volume = 0.4,
        pitch = 90.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 65 },
        preload = true,
    })
    builder:AddLoop("m_ambience_vent2b_pos2", {
        sounds = "bms_ambience/machine_ambience/m_ambience_vent2b.wav",
        volume = 0.7,
        pitch = 90.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 60 },
        preload = true,
    })
    builder:AddLoop("m_ambience_comp1_pos3", {
        sounds = "bms_ambience/machine_ambience/m_ambience_comp1.wav",
        volume = 0.8,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 3, soundLevel = 60 },
        preload = true,
    })
end)

ax.scapes:Register("insec_area3_lobby", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:17")
    builder:AddSubScape("insec_area3_lobby.base")
    builder:AddSubScape("ins.util.office", {
        volumeMultiplier = 0.5,
    })
    builder:AddSubScape("insec_area3_lockers.base")
    builder:AddLoop("vending_hum_pos0", {
        sounds = "bms_objects/vmachine/vending_hum.wav",
        volume = 0.8,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 65 },
        preload = true,
    })
    builder:AddLoop("vending_hum_a_pos1", {
        sounds = "bms_objects/vmachine/vending_hum_a.wav",
        volume = 0.8,
        pitch = 90.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 65 },
        preload = true,
    })
    builder:AddLoop("m_ambience_vent2_pos2", {
        sounds = "bms_ambience/machine_ambience/m_ambience_vent2.wav",
        volume = 0.4,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 65 },
        preload = true,
    })
    builder:AddLoop("m_ambience_comp1_pos3", {
        sounds = "bms_ambience/machine_ambience/m_ambience_comp1.wav",
        volume = 0.7,
        pitch = 90.0,
        spatial = { mode = "positional", positionKey = 3, soundLevel = 60 },
        preload = true,
    })
    builder:AddLoop("m_ambience_comp1a_pos4", {
        sounds = "bms_ambience/machine_ambience/m_ambience_comp1a.wav",
        volume = 0.8,
        pitch = 120.0,
        spatial = { mode = "positional", positionKey = 4, soundLevel = 60 },
        preload = true,
    })
    builder:AddLoop("m_ambience_vent1_pos5", {
        sounds = "bms_ambience/machine_ambience/m_ambience_vent1.wav",
        volume = 0.6,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 5, soundLevel = 60 },
        preload = true,
    })
end)

ax.scapes:Register("insec_area3_lockers", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:1")
    builder:AddSubScape("insec_area3_lockers.base")
    builder:AddSubScape("insec_area3_lobby.base", {
        volumeMultiplier = 0.5,
    })
    builder:AddLoop("hum1_pos0", {
        sounds = "bms_objects/hum/hum1.wav",
        volume = 0.8,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 65 },
        preload = true,
    })
    builder:AddLoop("m_ambience_vent2_pos1", {
        sounds = "bms_ambience/machine_ambience/m_ambience_vent2.wav",
        volume = 0.5,
        pitch = 90.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("m_ambience_vent2a_pos2", {
        sounds = "bms_ambience/machine_ambience/m_ambience_vent2a.wav",
        volume = 0.6,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("water_flow_loop1_pos3", {
        sounds = "ambient/water/water_flow_loop1.wav",
        volume = 0.8,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 3, soundLevel = 65 },
        preload = true,
    })
end)

ax.scapes:Register("insec_area3_sidehall", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:1")
    builder:AddSubScape("insec_area3_sidehall.base")
    builder:AddSubScape("ins.util.office", {
        volumeMultiplier = 0.3,
    })
    builder:AddLoop("hum1_pos0", {
        sounds = "bms_objects/hum/hum1.wav",
        volume = 0.8,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 65 },
        preload = true,
    })
    builder:AddLoop("m_ambience_vent2_pos1", {
        sounds = "bms_ambience/machine_ambience/m_ambience_vent2.wav",
        volume = 0.5,
        pitch = 90.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 60 },
        preload = true,
    })
    builder:AddLoop("m_ambience_vent2a_pos2", {
        sounds = "bms_ambience/machine_ambience/m_ambience_vent2a.wav",
        volume = 0.4,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 60 },
        preload = true,
    })
    builder:AddLoop("r_ambience_med14_pos3", {
        sounds = "bms_ambience/room_ambience/r_ambience_med14.wav",
        volume = 0.8,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 3, soundLevel = 65 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipeflow1_pos4", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipeflow1.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 4, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("m_ambience_lc5_pos5", {
        sounds = "bms_ambience/machine_ambience/m_ambience_lc5.wav",
        volume = 0.6,
        pitch = 120.0,
        spatial = { mode = "positional", positionKey = 5, soundLevel = 65 },
        preload = true,
    })
end)

ax.scapes:Register("insec_area3_elevator", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:2")
    builder:AddLoop("r_ambience_med12", {
        sounds = "bms_ambience/room_ambience/r_ambience_med12.wav",
        volume = 0.7,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 120 },
        preload = true,
    })
end)

ax.scapes:Register("insec_area3_upperhall", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:1")
    builder:AddSubScape("insec_area3_upperhall.base")
    builder:AddSubScape("ins.util.office", {
        volumeMultiplier = 0.4,
    })
    builder:AddLoop("m_ambience_pipe1_pos0", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipe1.wav",
        volume = 0.8,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 65 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipe1a_pos1", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipe1a.wav",
        volume = 0.6,
        pitch = 90.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("hum2_pos2", {
        sounds = "bms_objects/hum/hum2.wav",
        volume = 0.5,
        pitch = 90.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("m_ambience_vent2_pos3", {
        sounds = "bms_ambience/machine_ambience/m_ambience_vent2.wav",
        volume = 0.4,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 3, soundLevel = 70 },
        preload = true,
    })
end)

ax.scapes:Register("insec_area3_surveillance", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:1")
    builder:AddLoop("r_ambience_med8", {
        sounds = "bms_ambience/room_ambience/r_ambience_med8.wav",
        volume = 0.4,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 110 },
        preload = true,
    })
    builder:AddLoop("m_ambience_comp1_pos0", {
        sounds = "bms_ambience/machine_ambience/m_ambience_comp1.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 60 },
        preload = true,
    })
    builder:AddLoop("m_ambience_data1_pos1", {
        sounds = "bms_ambience/machine_ambience/m_ambience_data1.wav",
        volume = 0.4,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 60 },
        preload = true,
    })
    builder:AddLoop("m_ambience_comp3_pos2", {
        sounds = "bms_ambience/machine_ambience/m_ambience_comp3.wav",
        volume = 0.6,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("m_ambience_lc5_pos3", {
        sounds = "bms_ambience/machine_ambience/m_ambience_lc5.wav",
        volume = 0.5,
        pitch = 110.0,
        spatial = { mode = "positional", positionKey = 3, soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("insec_area3_stairwell", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:18")
    builder:AddSubScape("insec_area3_stairwell.base")
    builder:AddLoop("r_ambience_med9_pos0", {
        sounds = "bms_ambience/room_ambience/r_ambience_med9.wav",
        volume = 0.7,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 110 },
        preload = true,
    })
end)

ax.scapes:Register("insec_area3_armory", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:1")
    builder:AddLoop("r_ambience_med4", {
        sounds = "bms_ambience/room_ambience/r_ambience_med4.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 110 },
        preload = true,
    })
    builder:AddLoop("r_ambience_med10_pos0", {
        sounds = "bms_ambience/room_ambience/r_ambience_med10.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 110 },
        preload = true,
    })
    builder:AddLoop("m_ambience_comp3_pos1", {
        sounds = "bms_ambience/machine_ambience/m_ambience_comp3.wav",
        volume = 0.6,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("fan9_pos2", {
        sounds = "bms_objects/fans/fan9.wav",
        volume = 0.4,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 60 },
        preload = true,
    })
end)

ax.scapes:Register("insec_area3_range", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:1")
    builder:AddLoop("r_ambience_med12", {
        sounds = "bms_ambience/room_ambience/r_ambience_med12.wav",
        volume = 0.5,
        pitch = 110.0,
        spatial = { mode = "ambient", soundLevel = 110 },
        preload = true,
    })
    builder:AddLoop("m_ambience_electrichum4_pos0", {
        sounds = "bms_ambience/machine_ambience/m_ambience_electrichum4.wav",
        volume = 0.5,
        pitch = 110.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 70 },
        preload = true,
    })
end)

ax.scapes:Register("insec_area3_range_v2", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("r_ambience_med12", {
        sounds = "bms_ambience/room_ambience/r_ambience_med12.wav",
        volume = 0.1,
        pitch = 110.0,
        spatial = { mode = "ambient", soundLevel = 110 },
        preload = true,
    })
    builder:AddLoop("m_ambience_electrichum4_pos0", {
        sounds = "bms_ambience/machine_ambience/m_ambience_electrichum4.wav",
        volume = 0.02,
        pitch = 110.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 60 },
        preload = true,
    })
end)

ax.scapes:Register("insec_area3_generatorroom.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:AddLoop("r_ambience_lab1", {
        sounds = "bms_ambience/room_ambience/r_ambience_lab1.wav",
        volume = 0.7,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("r_ambience_industrial12", {
        sounds = "bms_ambience/room_ambience/r_ambience_industrial12.wav",
        volume = 0.4,
        pitch = 80.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("insec_area3_generatorroom_exit.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:AddLoop("r_ambience_lab2", {
        sounds = "bms_ambience/room_ambience/r_ambience_lab2.wav",
        volume = 0.7,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("r_ambience_small3", {
        sounds = "bms_ambience/room_ambience/r_ambience_small3.wav",
        volume = 1.0,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("insec_area3_platform.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:AddLoop("r_ambience_large8", {
        sounds = "bms_ambience/room_ambience/r_ambience_large8.wav",
        volume = 0.7,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 80 },
        preload = true,
    })
    builder:AddLoop("r_ambience_large10", {
        sounds = "bms_ambience/room_ambience/r_ambience_large10.wav",
        volume = 0.3,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 80 },
        preload = true,
    })
end)

ax.scapes:Register("insec_area3_maint1.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:AddLoop("r_ambience_large7", {
        sounds = "bms_ambience/room_ambience/r_ambience_large7.wav",
        volume = 0.7,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 80 },
        preload = true,
    })
    builder:AddLoop("corridor", {
        sounds = "ambient/atmosphere/corridor.wav",
        volume = 0.4,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 80 },
        preload = true,
    })
end)

ax.scapes:Register("insec_area3_maint2.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:AddLoop("r_ambience_large7", {
        sounds = "bms_ambience/room_ambience/r_ambience_large7.wav",
        volume = 0.3,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 80 },
        preload = true,
    })
    builder:AddLoop("corridor", {
        sounds = "ambient/atmosphere/corridor.wav",
        volume = 0.6,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 80 },
        preload = true,
    })
end)

ax.scapes:Register("insec_area3_drawbridge.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:AddLoop("r_ambience_large7", {
        sounds = "bms_ambience/room_ambience/r_ambience_large7.wav",
        volume = 0.4,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 80 },
        preload = true,
    })
    builder:AddLoop("underground", {
        sounds = "ambient/atmosphere/underground.wav",
        volume = 0.4,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 80 },
        preload = true,
    })
end)

ax.scapes:Register("insec_area3_maint3.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:AddLoop("corridor2", {
        sounds = "ambient/atmosphere/corridor2.wav",
        volume = 0.3,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 80 },
        preload = true,
    })
    builder:AddLoop("underground", {
        sounds = "ambient/atmosphere/underground.wav",
        volume = 0.3,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 80 },
        preload = true,
    })
end)

ax.scapes:Register("insec_area3_g_platform.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:AddLoop("r_ambience_large4", {
        sounds = "bms_ambience/room_ambience/r_ambience_large4.wav",
        volume = 0.6,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("r_ambience_wind1", {
        sounds = "bms_ambience/room_ambience/r_ambience_wind1.wav",
        volume = 0.4,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("insec_area3_g_entrance.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:AddLoop("r_ambience_small3", {
        sounds = "bms_ambience/room_ambience/r_ambience_small3.wav",
        volume = 0.7,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 80 },
        preload = true,
    })
end)

ax.scapes:Register("insec_area3_generatorroom", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:1")
    builder:AddSubScape("insec_area3_generatorroom.base")
    builder:AddLoop("field_loop3_pos0", {
        sounds = "ambient/levels/citadel/field_loop3.wav",
        volume = 0.7,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_lc4_pos1", {
        sounds = "bms_ambience/machine_ambience/m_ambience_lc4.wav",
        volume = 0.4,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("m_ambience_ind2_pos2", {
        sounds = "bms_ambience/machine_ambience/m_ambience_ind2.wav",
        volume = 0.5,
        pitch = 85.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 85 },
        preload = true,
    })
    builder:AddLoop("m_ambience_comp3_pos3", {
        sounds = "bms_ambience/machine_ambience/m_ambience_comp3.wav",
        volume = 0.4,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 3, soundLevel = 60 },
        preload = true,
    })
    builder:AddLoop("m_ambience_comp3a_pos4", {
        sounds = "bms_ambience/machine_ambience/m_ambience_comp3a.wav",
        volume = 0.4,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 4, soundLevel = 60 },
        preload = true,
    })
    builder:AddLoop("m_ambience_data1_pos5", {
        sounds = "bms_ambience/machine_ambience/m_ambience_data1.wav",
        volume = 0.7,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 5, soundLevel = 60 },
        preload = true,
    })
    builder:AddLoop("zapper_ambient_loop1_pos6", {
        sounds = "ambient/levels/citadel/zapper_ambient_loop1.wav",
        volume = 0.65,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 6, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_lc2_pos7", {
        sounds = "bms_ambience/machine_ambience/m_ambience_lc2.wav",
        volume = 0.4,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 7, soundLevel = 65 },
        preload = true,
    })
end)

ax.scapes:Register("insec_area3_generatorroom_exit", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:1")
    builder:AddSubScape("insec_area3_generatorroom_exit.base")
    builder:AddSubScape("insec_area3_platform.base", {
        volumeMultiplier = 0.65,
    })
    builder:AddLoop("fan7_pos0", {
        sounds = "bms_objects/fans/fan7.wav",
        volume = 0.6,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 65 },
        preload = true,
    })
    builder:AddLoop("r_ambience_med8_pos1", {
        sounds = "bms_ambience/room_ambience/r_ambience_med8.wav",
        volume = 0.7,
        pitch = 90.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 60 },
        preload = true,
    })
    builder:AddLoop("vending_hum_pos2", {
        sounds = "bms_objects/vmachine/vending_hum.wav",
        volume = 0.5,
        pitch = 85.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 80 },
        preload = true,
    })
end)

ax.scapes:Register("insec_area3_platform", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:1")
    builder:AddSubScape("insec_area3_platform.base")
    builder:AddLoop("m_ambience_electrichum1_pos0", {
        sounds = "bms_ambience/machine_ambience/m_ambience_electrichum1.wav",
        volume = 0.4,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 60 },
        preload = true,
    })
    builder:AddLoop("r_ambience_med8_pos1", {
        sounds = "bms_ambience/room_ambience/r_ambience_med8.wav",
        volume = 0.7,
        pitch = 90.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 60 },
        preload = true,
    })
    builder:AddLoop("vending_hum_pos2", {
        sounds = "bms_objects/vmachine/vending_hum.wav",
        volume = 0.5,
        pitch = 85.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 80 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipeflow1_pos3", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipeflow1.wav",
        volume = 0.6,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 3, soundLevel = 65 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipeflow1a_pos4", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipeflow1a.wav",
        volume = 0.6,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 4, soundLevel = 65 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipeflow1b_pos5", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipeflow1b.wav",
        volume = 0.6,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 5, soundLevel = 65 },
        preload = true,
    })
end)

ax.scapes:Register("insec_area3_maint1", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:1")
    builder:AddSubScape("insec_area3_maint1.base")
    builder:AddSubScape("ins.util.shaftFX", {
        volumeMultiplier = 0.35,
    })
    builder:AddLoop("m_ambience_electrichum1_pos0", {
        sounds = "bms_ambience/machine_ambience/m_ambience_electrichum1.wav",
        volume = 0.4,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 60 },
        preload = true,
    })
    builder:AddLoop("fan3_pos1", {
        sounds = "bms_objects/fans/fan3.wav",
        volume = 0.7,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 65 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipe3_pos2", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipe3.wav",
        volume = 0.6,
        pitch = 115.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 60 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipe2_pos3", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipe2.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 3, soundLevel = 60 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipeflow1_pos4", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipeflow1.wav",
        volume = 0.6,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 4, soundLevel = 65 },
        preload = true,
    })
end)

ax.scapes:Register("insec_area3_maint2", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:1")
    builder:AddSubScape("insec_area3_maint2.base")
    builder:AddLoop("m_ambience_electrichum2_pos0", {
        sounds = "bms_ambience/machine_ambience/m_ambience_electrichum2.wav",
        volume = 0.4,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 60 },
        preload = true,
    })
    builder:AddLoop("m_ambience_energy3_pos1", {
        sounds = "bms_ambience/machine_ambience/m_ambience_energy3.wav",
        volume = 0.7,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 65 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipe1_pos2", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipe1.wav",
        volume = 0.6,
        pitch = 115.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 60 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipe2_pos3", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipe2.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 3, soundLevel = 60 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipeflow1_pos4", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipeflow1.wav",
        volume = 0.6,
        pitch = 90.0,
        spatial = { mode = "positional", positionKey = 4, soundLevel = 70 },
        preload = true,
    })
end)

ax.scapes:Register("insec_area3_drawbridge", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:1")
    builder:AddSubScape("insec_area3_drawbridge.base")
    builder:AddSubScape("ins.util.shaftFX", {
        volumeMultiplier = 0.8,
    })
    builder:AddLoop("r_ambience_water7_pos0", {
        sounds = "bms_ambience/room_ambience/r_ambience_water7.wav",
        volume = 0.6,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 80 },
        preload = true,
    })
    builder:AddLoop("r_ambience_water8_pos1", {
        sounds = "bms_ambience/room_ambience/r_ambience_water8.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 80 },
        preload = true,
    })
    builder:AddLoop("m_ambience_motor1_pos2", {
        sounds = "bms_ambience/machine_ambience/m_ambience_motor1.wav",
        volume = 0.6,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 65 },
        preload = true,
    })
    builder:AddLoop("m_ambience_lc5_pos3", {
        sounds = "bms_ambience/machine_ambience/m_ambience_lc5.wav",
        volume = 0.7,
        pitch = 120.0,
        spatial = { mode = "positional", positionKey = 3, soundLevel = 65 },
        preload = true,
    })
    builder:AddLoop("m_ambience_electrical6_pos4", {
        sounds = "bms_ambience/machine_ambience/m_ambience_electrical6.wav",
        volume = 0.7,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 4, soundLevel = 60 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipe1_pos5", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipe1.wav",
        volume = 0.8,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 5, soundLevel = 60 },
        preload = true,
    })
end)

ax.scapes:Register("insec_area3_maint3", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:1")
    builder:AddSubScape("insec_area3_maint3.base")
    builder:AddSubScape("ins.util.shaftFX", {
        volumeMultiplier = 0.2,
    })
    builder:AddLoop("m_ambience_pipe1_pos0", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipe1.wav",
        volume = 0.8,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 60 },
        preload = true,
    })
    builder:AddLoop("m_ambience_electrichum1_pos1", {
        sounds = "bms_ambience/machine_ambience/m_ambience_electrichum1.wav",
        volume = 0.7,
        pitch = 80.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 65 },
        preload = true,
    })
    builder:AddLoop("m_ambience_electrichum4_pos2", {
        sounds = "bms_ambience/machine_ambience/m_ambience_electrichum4.wav",
        volume = 0.7,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 60 },
        preload = true,
    })
    builder:AddLoop("m_ambience_electrichum1a_pos3", {
        sounds = "bms_ambience/machine_ambience/m_ambience_electrichum1a.wav",
        volume = 0.4,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 3, soundLevel = 60 },
        preload = true,
    })
    builder:AddLoop("m_ambience_electrical6_pos4", {
        sounds = "bms_ambience/machine_ambience/m_ambience_electrical6.wav",
        volume = 0.7,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 4, soundLevel = 60 },
        preload = true,
    })
end)

ax.scapes:Register("insec_area3_g_platform", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:1")
    builder:AddSubScape("insec_area3_g_platform.base")
    builder:AddLoop("m_ambience_comp1_pos0", {
        sounds = "bms_ambience/machine_ambience/m_ambience_comp1.wav",
        volume = 0.6,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 65 },
        preload = true,
    })
    builder:AddLoop("hum1_pos1", {
        sounds = "bms_objects/hum/hum1.wav",
        volume = 0.7,
        pitch = 80.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 65 },
        preload = true,
    })
    builder:AddLoop("hum1a_pos2", {
        sounds = "bms_objects/hum/hum1a.wav",
        volume = 0.7,
        pitch = 80.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 65 },
        preload = true,
    })
    builder:AddLoop("m_ambience_energy5_pos3", {
        sounds = "bms_ambience/machine_ambience/m_ambience_energy5.wav",
        volume = 0.7,
        pitch = 140.0,
        spatial = { mode = "positional", positionKey = 3, soundLevel = 65 },
        preload = true,
    })
    builder:AddLoop("m_ambience_vent1_pos4", {
        sounds = "bms_ambience/machine_ambience/m_ambience_vent1.wav",
        volume = 0.7,
        pitch = 90.0,
        spatial = { mode = "positional", positionKey = 4, soundLevel = 60 },
        preload = true,
    })
    builder:AddLoop("m_ambience_vent1a_pos5", {
        sounds = "bms_ambience/machine_ambience/m_ambience_vent1a.wav",
        volume = 0.7,
        pitch = 90.0,
        spatial = { mode = "positional", positionKey = 5, soundLevel = 60 },
        preload = true,
    })
end)

ax.scapes:Register("insec_area3_g_entrance", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:1")
    builder:AddSubScape("insec_area3_g_entrance.base")
    builder:AddSubScape("insec_area3_g_platform.base", {
        volumeMultiplier = 0.35,
    })
    builder:AddLoop("m_ambience_comp1_pos0", {
        sounds = "bms_ambience/machine_ambience/m_ambience_comp1.wav",
        volume = 0.6,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 65 },
        preload = true,
    })
    builder:AddLoop("r_ambience_large4_pos1", {
        sounds = "bms_ambience/room_ambience/r_ambience_large4.wav",
        volume = 0.3,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("vending_hum_pos2", {
        sounds = "bms_objects/vmachine/vending_hum.wav",
        volume = 0.7,
        pitch = 90.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 60 },
        preload = true,
    })
    builder:AddLoop("m_ambience_comp3_pos3", {
        sounds = "bms_ambience/machine_ambience/m_ambience_comp3.wav",
        volume = 0.7,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 3, soundLevel = 60 },
        preload = true,
    })
    builder:AddLoop("fan9_pos4", {
        sounds = "bms_objects/fans/fan9.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 4, soundLevel = 60 },
        preload = true,
    })
    builder:AddLoop("hum1_pos5", {
        sounds = "bms_objects/hum/hum1.wav",
        volume = 0.4,
        pitch = 80.0,
        spatial = { mode = "positional", positionKey = 5, soundLevel = 65 },
        preload = true,
    })
    builder:AddLoop("hum1a_pos6", {
        sounds = "bms_objects/hum/hum1a.wav",
        volume = 0.4,
        pitch = 80.0,
        spatial = { mode = "positional", positionKey = 6, soundLevel = 65 },
        preload = true,
    })
end)

ax.scapes:Register("insec_hp_checkpoint.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:AddLoop("r_ambience_small3", {
        sounds = "bms_ambience/room_ambience/r_ambience_small3.wav",
        volume = 0.8,
        pitch = 110.0,
        spatial = { mode = "ambient", soundLevel = 80 },
        preload = true,
    })
    builder:AddLoop("r_ambience_lab1", {
        sounds = "bms_ambience/room_ambience/r_ambience_lab1.wav",
        volume = 0.5,
        pitch = 80.0,
        spatial = { mode = "ambient", soundLevel = 80 },
        preload = true,
    })
end)

ax.scapes:Register("insec_hp_river.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:AddLoop("r_ambience_large8", {
        sounds = "bms_ambience/room_ambience/r_ambience_large8.wav",
        volume = 0.8,
        pitch = 110.0,
        spatial = { mode = "ambient", soundLevel = 80 },
        preload = true,
    })
end)

ax.scapes:Register("insec_hp_entrance.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:AddLoop("r_ambience_med9", {
        sounds = "bms_ambience/room_ambience/r_ambience_med9.wav",
        volume = 0.8,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 80 },
        preload = true,
    })
end)

ax.scapes:Register("insec_hp_warehouseA.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:AddLoop("r_ambience_med10", {
        sounds = "bms_ambience/room_ambience/r_ambience_med10.wav",
        volume = 0.6,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 80 },
        preload = true,
    })
    builder:AddLoop("r_ambience_industrial32", {
        sounds = "bms_ambience/room_ambience/r_ambience_industrial32.wav",
        volume = 0.2,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 80 },
        preload = true,
    })
end)

ax.scapes:Register("insec_hp_warehouseB.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:AddLoop("r_ambience_industrial21", {
        sounds = "bms_ambience/room_ambience/r_ambience_industrial21.wav",
        volume = 0.6,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 80 },
        preload = true,
    })
    builder:AddLoop("r_ambience_industrial28", {
        sounds = "bms_ambience/room_ambience/r_ambience_industrial28.wav",
        volume = 0.4,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 80 },
        preload = true,
    })
end)

ax.scapes:Register("insec_hp_garage.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:AddLoop("r_ambience_large8", {
        sounds = "bms_ambience/room_ambience/r_ambience_large8.wav",
        volume = 0.8,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 80 },
        preload = true,
    })
    builder:AddLoop("r_ambience_industrial1", {
        sounds = "bms_ambience/room_ambience/r_ambience_industrial1.wav",
        volume = 0.4,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 80 },
        preload = true,
    })
end)

ax.scapes:Register("insec_hp_generators.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:AddLoop("r_ambience_med10", {
        sounds = "bms_ambience/room_ambience/r_ambience_med10.wav",
        volume = 0.6,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 80 },
        preload = true,
    })
    builder:AddLoop("r_ambience_industrial1", {
        sounds = "bms_ambience/room_ambience/r_ambience_industrial1.wav",
        volume = 0.3,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 80 },
        preload = true,
    })
end)

ax.scapes:Register("insec_hp_fanroom.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:AddLoop("m_ambience_lc20", {
        sounds = "bms_ambience/machine_ambience/m_ambience_lc20.wav",
        volume = 0.7,
        pitch = 120.0,
        spatial = { mode = "ambient", soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("fan4", {
        sounds = "bms_objects/fans/fan4.wav",
        volume = 0.5,
        pitch = 80.0,
        spatial = { mode = "ambient", soundLevel = 70 },
        preload = true,
    })
end)

ax.scapes:Register("insec_hp_waitingarea.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:AddLoop("r_ambience_small3", {
        sounds = "bms_ambience/room_ambience/r_ambience_small3.wav",
        volume = 0.6,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 80 },
        preload = true,
    })
end)

ax.scapes:Register("insec_hp_elev_maintenance.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:AddLoop("r_ambience_med9", {
        sounds = "bms_ambience/room_ambience/r_ambience_med9.wav",
        volume = 0.6,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("insec_hp_elev_shaft.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:AddLoop("r_ambience_disaster_rumble1", {
        sounds = "bms_ambience/room_ambience/r_ambience_disaster_rumble1.wav",
        volume = 0.8,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 80 },
        preload = true,
    })
    builder:AddLoop("r_ambience_large4", {
        sounds = "bms_ambience/room_ambience/r_ambience_large4.wav",
        volume = 0.6,
        pitch = 120.0,
        spatial = { mode = "ambient", soundLevel = 80 },
        preload = true,
    })
end)

ax.scapes:Register("insec_hp_checkpoint", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:7")
    builder:AddSubScape("insec_hp_checkpoint.base")
    builder:AddLoop("m_ambience_electrichum2_pos0", {
        sounds = "bms_ambience/machine_ambience/m_ambience_electrichum2.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 60 },
        preload = true,
    })
    builder:AddLoop("m_ambience_comp1_pos1", {
        sounds = "bms_ambience/machine_ambience/m_ambience_comp1.wav",
        volume = 0.4,
        pitch = 90.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("m_ambience_comp3_pos2", {
        sounds = "bms_ambience/machine_ambience/m_ambience_comp3.wav",
        volume = 0.7,
        pitch = 90.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 65 },
        preload = true,
    })
end)

ax.scapes:Register("insec_hp_checkpoint_s2", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:7")
    builder:AddSubScape("insec_hp_checkpoint.base")
    builder:AddLoop("m_ambience_electrichum2_pos0", {
        sounds = "bms_ambience/machine_ambience/m_ambience_electrichum2.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 60 },
        preload = true,
    })
    builder:AddLoop("m_ambience_comp1_pos1", {
        sounds = "bms_ambience/machine_ambience/m_ambience_comp1.wav",
        volume = 0.4,
        pitch = 90.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("m_ambience_comp3_pos2", {
        sounds = "bms_ambience/machine_ambience/m_ambience_comp3.wav",
        volume = 0.7,
        pitch = 90.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 65 },
        preload = true,
    })
    builder:AddLoop("r_ambience_water21_pos3", {
        sounds = "bms_ambience/room_ambience/r_ambience_water21.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 3, soundLevel = 80 },
        preload = true,
    })
    builder:AddLoop("r_ambience_water10_pos4", {
        sounds = "bms_ambience/room_ambience/r_ambience_water10.wav",
        volume = 0.7,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 4, soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("insec_hp_river", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:7")
    builder:AddSubScape("insec_hp_river.base")
    builder:AddLoop("r_ambience_water21_pos0", {
        sounds = "bms_ambience/room_ambience/r_ambience_water21.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 80 },
        preload = true,
    })
    builder:AddLoop("r_ambience_water10_pos1", {
        sounds = "bms_ambience/room_ambience/r_ambience_water10.wav",
        volume = 0.7,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("insec_hp_entrance", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:17")
    builder:AddSubScape("insec_hp_entrance.base")
    builder:AddSubScape("ins.util.industrial", {
        volumeMultiplier = 0.3,
    })
    builder:AddLoop("m_ambience_electrichum1_pos0", {
        sounds = "bms_ambience/machine_ambience/m_ambience_electrichum1.wav",
        volume = 0.3,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 60 },
        preload = true,
    })
    builder:AddLoop("m_ambience_electrichum1a_pos1", {
        sounds = "bms_ambience/machine_ambience/m_ambience_electrichum1a.wav",
        volume = 0.7,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 60 },
        preload = true,
    })
    builder:AddLoop("hum1_pos2", {
        sounds = "bms_objects/hum/hum1.wav",
        volume = 0.6,
        pitch = 120.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 60 },
        preload = true,
    })
    builder:AddLoop("hum1a_pos3", {
        sounds = "bms_objects/hum/hum1a.wav",
        volume = 0.6,
        pitch = 120.0,
        spatial = { mode = "positional", positionKey = 3, soundLevel = 60 },
        preload = true,
    })
    builder:AddLoop("hum2_pos4", {
        sounds = "bms_objects/hum/hum2.wav",
        volume = 0.7,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 4, soundLevel = 65 },
        preload = true,
    })
    builder:AddLoop("r_ambience_water21_pos5", {
        sounds = "bms_ambience/room_ambience/r_ambience_water21.wav",
        volume = 0.25,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 5, soundLevel = 80 },
        preload = true,
    })
    builder:AddLoop("r_ambience_water10_pos6", {
        sounds = "bms_ambience/room_ambience/r_ambience_water10.wav",
        volume = 0.35,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 6, soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("insec_hp_warehouseA", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:10")
    builder:AddSubScape("insec_hp_warehouseA.base")
    builder:AddSubScape("ins.util.industrial", {
        volumeMultiplier = 0.4,
    })
    builder:AddLoop("m_ambience_misc10_pos0", {
        sounds = "bms_ambience/machine_ambience/m_ambience_misc10.wav",
        volume = 0.7,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_electrichum1_pos1", {
        sounds = "bms_ambience/machine_ambience/m_ambience_electrichum1.wav",
        volume = 0.2,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 60 },
        preload = true,
    })
    builder:AddLoop("m_ambience_motor1_pos2", {
        sounds = "bms_ambience/machine_ambience/m_ambience_motor1.wav",
        volume = 0.6,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 70 },
        preload = true,
    })
end)

ax.scapes:Register("insec_hp_warehouseB", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:10")
    builder:AddSubScape("insec_hp_warehouseB.base")
    builder:AddSubScape("ins.util.industrial", {
        volumeMultiplier = 0.5,
    })
    builder:AddLoop("m_ambience_pipe2_pos0", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipe2.wav",
        volume = 0.7,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("fan2_pos1", {
        sounds = "bms_objects/fans/fan2.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("fan2a_pos2", {
        sounds = "bms_objects/fans/fan2a.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("m_ambience_electrichum2_pos3", {
        sounds = "bms_ambience/machine_ambience/m_ambience_electrichum2.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 3, soundLevel = 60 },
        preload = true,
    })
    builder:AddLoop("m_ambience_vent1_pos4", {
        sounds = "bms_ambience/machine_ambience/m_ambience_vent1.wav",
        volume = 0.4,
        pitch = 120.0,
        spatial = { mode = "positional", positionKey = 4, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("r_ambience_med12_pos5", {
        sounds = "bms_ambience/room_ambience/r_ambience_med12.wav",
        volume = 0.7,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 5, soundLevel = 90 },
        preload = true,
    })
end)

ax.scapes:Register("insec_hp_garage", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:19")
    builder:AddSubScape("insec_hp_garage.base")
    builder:AddSubScape("ins.util.industrial", {
        volumeMultiplier = 0.4,
    })
    builder:AddLoop("fan6_pos0", {
        sounds = "bms_objects/fans/fan6.wav",
        volume = 0.7,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 80 },
        preload = true,
    })
    builder:AddLoop("fan2_pos1", {
        sounds = "bms_objects/fans/fan2.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("fan2a_pos2", {
        sounds = "bms_objects/fans/fan2a.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("m_ambience_electrichum1_pos3", {
        sounds = "bms_ambience/machine_ambience/m_ambience_electrichum1.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 3, soundLevel = 60 },
        preload = true,
    })
    builder:AddLoop("fan4_pos4", {
        sounds = "bms_objects/fans/fan4.wav",
        volume = 0.4,
        pitch = 120.0,
        spatial = { mode = "positional", positionKey = 4, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("fan4a_pos5", {
        sounds = "bms_objects/fans/fan4a.wav",
        volume = 0.4,
        pitch = 120.0,
        spatial = { mode = "positional", positionKey = 5, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("r_ambience_med14_pos6", {
        sounds = "bms_ambience/room_ambience/r_ambience_med14.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 6, soundLevel = 90 },
        preload = true,
    })
    builder:AddLoop("m_ambience_motor2_pos7", {
        sounds = "bms_ambience/machine_ambience/m_ambience_motor2.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 7, soundLevel = 70 },
        preload = true,
    })
end)

ax.scapes:Register("insec_hp_generators", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:9")
    builder:AddSubScape("insec_hp_generators.base")
    builder:AddLoop("m_ambience_motor1_pos0", {
        sounds = "bms_ambience/machine_ambience/m_ambience_motor1.wav",
        volume = 0.3,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("r_ambience_industrial12_pos1", {
        sounds = "bms_ambience/room_ambience/r_ambience_industrial12.wav",
        volume = 0.6,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 85 },
        preload = true,
    })
    builder:AddLoop("m_ambience_ind29_pos2", {
        sounds = "bms_ambience/machine_ambience/m_ambience_ind29.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 85 },
        preload = true,
    })
    builder:AddLoop("fan7_pos3", {
        sounds = "bms_objects/fans/fan7.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 3, soundLevel = 60 },
        preload = true,
    })
end)

ax.scapes:Register("insec_hp_fanroom", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:17")
    builder:AddSubScape("insec_hp_fanroom.base")
end)

ax.scapes:Register("insec_hp_waitingarea", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:17")
    builder:AddSubScape("insec_hp_waitingarea.base")
    builder:AddSubScape("insec_hp_fanroom.base")
    builder:AddLoop("vending_hum_pos0", {
        sounds = "bms_objects/vmachine/vending_hum.wav",
        volume = 0.7,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("m_ambience_electrichum1_pos4", {
        sounds = "bms_ambience/machine_ambience/m_ambience_electrichum1.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 4, soundLevel = 60 },
        preload = true,
    })
    builder:AddLoop("fan9_pos5", {
        sounds = "bms_objects/fans/fan9.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 5, soundLevel = 65 },
        preload = true,
    })
    builder:AddLoop("fan3_pos6", {
        sounds = "bms_objects/fans/fan3.wav",
        volume = 0.5,
        pitch = 85.0,
        spatial = { mode = "positional", positionKey = 6, soundLevel = 65 },
        preload = true,
    })
    builder:AddLoop("r_ambience_med3_pos7", {
        sounds = "bms_ambience/room_ambience/r_ambience_med3.wav",
        volume = 0.45,
        pitch = 90.0,
        spatial = { mode = "positional", positionKey = 7, soundLevel = 95 },
        preload = true,
    })
end)

ax.scapes:Register("insec_hp_waitingarea_s2", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:17")
    builder:AddSubScape("insec_hp_waitingarea.base")
    builder:AddSubScape("insec_hp_elev_maintenance.base")
    builder:AddLoop("m_ambience_energy3_pos0", {
        sounds = "bms_ambience/machine_ambience/m_ambience_energy3.wav",
        volume = 0.37,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("m_ambience_electrichum1_pos4", {
        sounds = "bms_ambience/machine_ambience/m_ambience_electrichum1.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 4, soundLevel = 60 },
        preload = true,
    })
    builder:AddLoop("fan9_pos5", {
        sounds = "bms_objects/fans/fan9.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 5, soundLevel = 65 },
        preload = true,
    })
    builder:AddLoop("fan3_pos6", {
        sounds = "bms_objects/fans/fan3.wav",
        volume = 0.5,
        pitch = 85.0,
        spatial = { mode = "positional", positionKey = 6, soundLevel = 65 },
        preload = true,
    })
    builder:AddLoop("r_ambience_med3_pos7", {
        sounds = "bms_ambience/room_ambience/r_ambience_med3.wav",
        volume = 0.45,
        pitch = 90.0,
        spatial = { mode = "positional", positionKey = 7, soundLevel = 95 },
        preload = true,
    })
end)

ax.scapes:Register("insec_hp_elev_maintenance", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:18")
    builder:AddSubScape("insec_hp_elev_maintenance.base")
    builder:AddLoop("m_ambience_energy3_pos0", {
        sounds = "bms_ambience/machine_ambience/m_ambience_energy3.wav",
        volume = 0.7,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("m_ambience_misc7_pos1", {
        sounds = "bms_ambience/machine_ambience/m_ambience_misc7.wav",
        volume = 0.7,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 65 },
        preload = true,
    })
    builder:AddLoop("r_ambience_med13_pos2", {
        sounds = "bms_ambience/room_ambience/r_ambience_med13.wav",
        volume = 0.7,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 65 },
        preload = true,
    })
    builder:AddLoop("r_ambience_med3_pos7", {
        sounds = "bms_ambience/room_ambience/r_ambience_med3.wav",
        volume = 0.3,
        pitch = 90.0,
        spatial = { mode = "positional", positionKey = 7, soundLevel = 95 },
        preload = true,
    })
end)

ax.scapes:Register("insec_hp_elev_shaft", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:4")
    builder:AddSubScape("insec_hp_elev_shaft.base")
    builder:AddSubScape("ins.util.shaftFX", {
        volumeMultiplier = 0.5,
    })
end)

ax.scapes:Register("insec_hp_elev_chamber", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:9")
    builder:AddLoop("r_ambience_disaster_rumble6", {
        sounds = "bms_ambience/room_ambience/r_ambience_disaster_rumble6.wav",
        volume = 0.8,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 120 },
        preload = true,
    })
    builder:AddLoop("r_ambience_industrial35", {
        sounds = "bms_ambience/room_ambience/r_ambience_industrial35.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 110 },
        preload = true,
    })
end)

ax.scapes:Register("insec_hp_waitingarea_sidehall", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:17")
    builder:AddSubScape("insec_hp_waitingarea", {
        volumeMultiplier = 0.4,
    })
    builder:AddLoop("hum1_pos1", {
        sounds = "bms_objects/hum/hum1.wav",
        volume = 0.7,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 65 },
        preload = true,
    })
    builder:AddLoop("hum1a_pos2", {
        sounds = "bms_objects/hum/hum1a.wav",
        volume = 0.7,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 65 },
        preload = true,
    })
    builder:AddLoop("hum1b_pos3", {
        sounds = "bms_objects/hum/hum1b.wav",
        volume = 0.7,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 3, soundLevel = 65 },
        preload = true,
    })
    builder:AddLoop("m_ambience_electrichum1_pos4", {
        sounds = "bms_ambience/machine_ambience/m_ambience_electrichum1.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 4, soundLevel = 60 },
        preload = true,
    })
    builder:AddLoop("fan9_pos5", {
        sounds = "bms_objects/fans/fan9.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 5, soundLevel = 65 },
        preload = true,
    })
    builder:AddLoop("fan3_pos6", {
        sounds = "bms_objects/fans/fan3.wav",
        volume = 0.5,
        pitch = 85.0,
        spatial = { mode = "positional", positionKey = 6, soundLevel = 65 },
        preload = true,
    })
    builder:AddLoop("r_ambience_med3_pos7", {
        sounds = "bms_ambience/room_ambience/r_ambience_med3.wav",
        volume = 0.5,
        pitch = 90.0,
        spatial = { mode = "positional", positionKey = 7, soundLevel = 95 },
        preload = true,
    })
end)
