-- Auto-generated by tools/generate_scapes_from_soundscapes.py
-- Source: C:/Program Files (x86)/Steam/steamapps/common/GarrysMod/garrysmod/addons/rp_black_mesa_facility/scripts/soundscapes_c1a0.txt
-- Scapes emitted: 61


ax.scapes:Register("c1a0.computers", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:AddLoop("m_ambience_comp1", {
        sounds = "bms_ambience/machine_ambience/m_ambience_comp1.wav",
        volume = 1.0,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_comp2", {
        sounds = "bms_ambience/machine_ambience/m_ambience_comp2.wav",
        volume = 1.0,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_comp3", {
        sounds = "bms_ambience/machine_ambience/m_ambience_comp3.wav",
        volume = 1.0,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a0.computers2", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:AddLoop("m_ambience_comp1a", {
        sounds = "bms_ambience/machine_ambience/m_ambience_comp1a.wav",
        volume = 1.0,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_comp2a", {
        sounds = "bms_ambience/machine_ambience/m_ambience_comp2a.wav",
        volume = 1.0,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_comp3a", {
        sounds = "bms_ambience/machine_ambience/m_ambience_comp3a.wav",
        volume = 1.0,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a0a.hallway.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("r_ambience_med4", {
        sounds = "BMS_ambience/room_ambience/r_ambience_med4.wav",
        volume = 0.8,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a0a.networkroom.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("r_ambience_med4", {
        sounds = "BMS_ambience/room_ambience/r_ambience_med4.wav",
        volume = 0.6,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("r_ambience_lab1", {
        sounds = "BMS_ambience/room_ambience/r_ambience_lab1.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a0a.lockerroom.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("r_ambience_med4", {
        sounds = "BMS_ambience/room_ambience/r_ambience_med4.wav",
        volume = 0.7,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("hum1", {
        sounds = "BMS_objects/hum/hum1.wav",
        volume = 0.15,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a0a.devlabs.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("r_ambience_med4", {
        sounds = "BMS_ambience/room_ambience/r_ambience_med4.wav",
        volume = 0.6,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("r_ambience_lab1", {
        sounds = "BMS_ambience/room_ambience/r_ambience_lab1.wav",
        volume = 0.7,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a0a.elevatorshaft.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("r_ambience_large2", {
        sounds = "BMS_ambience/room_ambience/r_ambience_large2.wav",
        volume = 0.7,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a0a.airlock.util_pos4-7", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("m_ambience_comp1_pos4", {
        sounds = "bms_ambience/machine_ambience/m_ambience_comp1.wav",
        volume = 0.15,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 4, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_electrichum1b_pos5", {
        sounds = "bms_ambience/machine_ambience/m_ambience_electrichum1b.wav",
        volume = 0.08,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 5, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_misc10_pos6", {
        sounds = "bms_ambience/machine_ambience/m_ambience_misc10.wav",
        volume = 0.25,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 6, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_misc10a_pos7", {
        sounds = "bms_ambience/machine_ambience/m_ambience_misc10a.wav",
        volume = 0.25,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 7, soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a0a.lob.util_pos0", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("m_ambience_electrichum1_pos0", {
        sounds = "bms_ambience/machine_ambience/m_ambience_electrichum1.wav",
        volume = 0.06,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a0a.lob.util_pos2", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("m_ambience_comp1a_pos2", {
        sounds = "bms_ambience/machine_ambience/m_ambience_comp1a.wav",
        volume = 0.18,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a0a.hnet.util_pos1-2", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:3")
    builder:AddLoop("m_ambience_vent2_pos1", {
        sounds = "bms_ambience/machine_ambience/m_ambience_vent2.wav",
        volume = 0.25,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("m_ambience_electrichum1_pos2", {
        sounds = "bms_ambience/machine_ambience/m_ambience_electrichum1.wav",
        volume = 0.05,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a0a.hdev.util_pos0", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("m_ambience_electrichum1a_pos0", {
        sounds = "bms_ambience/machine_ambience/m_ambience_electrichum1a.wav",
        volume = 0.2,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a0a.hdev.util_pos3", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:AddLoop("m_ambience_pipeflow1_pos3", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipeflow1.wav",
        volume = 0.25,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 3, soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a0a.wb.util_pos6-7", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:3")
    builder:AddLoop("m_ambience_vent1_pos6", {
        sounds = "bms_ambience/machine_ambience/m_ambience_vent1.wav",
        volume = 0.35,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 6, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_vent1a_pos7", {
        sounds = "bms_ambience/machine_ambience/m_ambience_vent1a.wav",
        volume = 0.35,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 7, soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a0a.lockerroom.util_pos6-7", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("m_ambience_comp2_pos6", {
        sounds = "bms_ambience/machine_ambience/m_ambience_comp2.wav",
        volume = 0.15,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 6, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_lc20_pos7", {
        sounds = "bms_ambience/machine_ambience/m_ambience_lc20.wav",
        volume = 0.55,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 7, soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a0a.lockerroom.util_posblend", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("r_ambience_med4", {
        sounds = "BMS_ambience/room_ambience/r_ambience_med4.wav",
        volume = 0.7,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("hum1", {
        sounds = "BMS_objects/hum/hum1.wav",
        volume = 0.15,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a0a.plza.util_pos0-1", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("m_ambience_electrichum1_pos0", {
        sounds = "bms_ambience/machine_ambience/m_ambience_electrichum1.wav",
        volume = 0.25,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_electrichum1a_pos1", {
        sounds = "bms_ambience/machine_ambience/m_ambience_electrichum1a.wav",
        volume = 0.25,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a0a.brk.util_pos4-5", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("vending_hum_a_pos4", {
        sounds = "bms_objects/vmachine/vending_hum_a.wav",
        volume = 0.25,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 4, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("vending_hum_b_pos5", {
        sounds = "bms_objects/vmachine/vending_hum_b.wav",
        volume = 0.25,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 5, soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a0a.devlab.util_pos5-7", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("m_ambience_comp3_pos5", {
        sounds = "bms_ambience/machine_ambience/m_ambience_comp3.wav",
        volume = 0.55,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 5, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_comp3a_pos6", {
        sounds = "bms_ambience/machine_ambience/m_ambience_comp3a.wav",
        volume = 0.25,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 6, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_comp2_pos7", {
        sounds = "bms_ambience/machine_ambience/m_ambience_comp2.wav",
        volume = 0.25,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 7, soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a0a.devlab.util_posblend", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("r_ambience_lab1a_pos4", {
        sounds = "BMS_ambience/room_ambience/r_ambience_lab1a.wav",
        volume = 1.0,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 4, soundLevel = 70 },
        preload = true,
    })
end)

ax.scapes:Register("c1a0a.am_catwalk", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:10")
    builder:AddSubScape("ib.am.catwalk.base")
    builder:AddSubScape("c1a0a.airlock.util_pos4-7", {
        volumeMultiplier = 0.9,
    })
end)

ax.scapes:Register("c1a0a.airlock", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:2")
    builder:AddSubScape("c1a0a.hallway.base")
    builder:AddSubScape("c1a0a.airlock.util_pos4-7")
    builder:AddSubScape("c1a0a.lob.util_pos2")
    builder:AddSubScape("c1a0a.lob.util_pos0")
end)

ax.scapes:Register("c1a0a.lobby", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:2")
    builder:AddSubScape("c1a0a.hallway.base")
    builder:AddSubScape("c1a0a.airlock.util_pos4-7", {
        volumeMultiplier = 0.65,
    })
    builder:AddSubScape("c1a0a.lob.util_pos2")
    builder:AddSubScape("c1a0a.lob.util_pos0")
end)

ax.scapes:Register("c1a0a.hallway_net", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:2")
    builder:AddSubScape("c1a0a.hallway.base")
    builder:AddSubScape("c1a0a.hdev.util_pos0")
    builder:AddSubScape("c1a0a.hnet.util_pos1-2")
    builder:AddSubScape("c1a0a.wb.util_pos6-7")
    builder:AddSubScape("c1a0a.devlab.util_posblend", {
        volumeMultiplier = 0.5,
    })
end)

ax.scapes:Register("c1a0a.networkroom", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:2")
    builder:AddSubScape("c1a0a.networkroom.base")
    builder:AddSubScape("c1a0.computers", {
        volumeMultiplier = 0.2,
    })
    builder:AddSubScape("c1a0.computers2", {
        volumeMultiplier = 0.2,
    })
end)

ax.scapes:Register("c1a0a.hallway_dev", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:2")
    builder:AddSubScape("c1a0a.hallway.base")
    builder:AddSubScape("c1a0a.hdev.util_pos3")
    builder:AddSubScape("c1a0a.devlab.util_posblend", {
        volumeMultiplier = 0.65,
    })
end)

ax.scapes:Register("c1a0a.devlabs", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:2")
    builder:AddSubScape("c1a0a.devlabs.base")
    builder:AddSubScape("c1a0a.hdev.util_pos0")
    builder:AddSubScape("c1a0a.devlab.util_pos5-7")
end)

ax.scapes:Register("c1a0a.hallway_wb", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:2")
    builder:AddSubScape("c1a0a.hallway.base")
    builder:AddSubScape("c1a0a.wb.util_pos6-7")
    builder:AddSubScape("c1a0a.hnet.util_pos1-2")
end)

ax.scapes:Register("c1a0a.hallway_brk", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:2")
    builder:AddSubScape("c1a0a.hallway.base")
    builder:AddSubScape("c1a0a.brk.util_pos4-5")
    builder:AddSubScape("c1a0a.lockerroom.util_posblend")
end)

ax.scapes:Register("c1a0a.breakroom", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:2")
    builder:AddSubScape("c1a0a.hallway.base", {
        volumeMultiplier = 0.8,
    })
    builder:AddSubScape("c1a0a.brk.util_pos4-5")
end)

ax.scapes:Register("c1a0a.lockerroom", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:2")
    builder:AddSubScape("c1a0a.lockerroom.base")
    builder:AddSubScape("c1a0a.lockerroom.util_pos6-7")
    builder:AddSubScape("c1a0a.lockerroom.util_posblend")
end)

ax.scapes:Register("c1a0a.labs", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:2")
    builder:AddLoop("r_ambience_med4", {
        sounds = "BMS_ambience/room_ambience/r_ambience_med4.wav",
        volume = 0.6,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("r_ambience_lab1", {
        sounds = "BMS_ambience/room_ambience/r_ambience_lab1.wav",
        volume = 0.7,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a0a.hallway_ret", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:2")
    builder:AddSubScape("c1a0a.hallway.base")
    builder:AddSubScape("c1a0a.hdev.util_pos3")
    builder:AddSubScape("c1a0a.plza.util_pos0-1")
end)

ax.scapes:Register("c1a0a.plaza", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:2")
    builder:AddSubScape("c1a0a.hallway.base")
    builder:AddSubScape("c1a0a.plza.util_pos0-1")
end)

ax.scapes:Register("c1a0a.elevatorshaft", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:10")
    builder:AddSubScape("c1a0a.elevatorshaft.base")
    builder:AddSubScape("c1a0b.h3.util_pos0-3")
    builder:AddSubScape("c1a0b.h3.util_pos4-7")
end)

ax.scapes:Register("c1a0b.hallway.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("r_ambience_med4", {
        sounds = "BMS_ambience/room_ambience/r_ambience_med4.wav",
        volume = 0.8,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a0b.contolroom.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("r_ambience_med4", {
        sounds = "BMS_ambience/room_ambience/r_ambience_med4.wav",
        volume = 0.6,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("r_ambience_lab1", {
        sounds = "BMS_ambience/room_ambience/r_ambience_lab1.wav",
        volume = 0.7,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a0b.h3.util_pos0-3", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("m_ambience_comp1_pos0", {
        sounds = "bms_ambience/machine_ambience/m_ambience_comp1.wav",
        volume = 0.25,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_comp2_pos1", {
        sounds = "bms_ambience/machine_ambience/m_ambience_comp2.wav",
        volume = 0.45,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_comp3_pos2", {
        sounds = "bms_ambience/machine_ambience/m_ambience_comp3.wav",
        volume = 0.45,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_electrichum1a_pos3", {
        sounds = "bms_ambience/machine_ambience/m_ambience_electrichum1a.wav",
        volume = 0.1,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 3, soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a0b.h3.util_pos4-7", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("m_ambience_electrichum1_pos4", {
        sounds = "bms_ambience/machine_ambience/m_ambience_electrichum1.wav",
        volume = 0.1,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 4, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipe1_pos5", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipe1.wav",
        volume = 0.35,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 5, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("labdrone2_pos7", {
        sounds = "hl1/ambience/labdrone2.wav",
        volume = 0.95,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 7, soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a0b.t1.util_pos1-3", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("m_ambience_comp3_pos1", {
        sounds = "bms_ambience/machine_ambience/m_ambience_comp3.wav",
        volume = 0.25,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipeflow2_pos2", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipeflow2.wav",
        volume = 0.305,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipeflow1_pos3", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipeflow1.wav",
        volume = 0.305,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 3, soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a0b.h1.util_pos5", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("m_ambience_comp1_pos5", {
        sounds = "bms_ambience/machine_ambience/m_ambience_comp1.wav",
        volume = 0.25,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 5, soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a0b.ionroom.util_pos4-5", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("m_ambience_comp1a_pos4", {
        sounds = "bms_ambience/machine_ambience/m_ambience_comp1a.wav",
        volume = 0.25,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 4, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_comp1b_pos5", {
        sounds = "bms_ambience/machine_ambience/m_ambience_comp1b.wav",
        volume = 0.25,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 5, soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a0b.ionroom.util_pos6-7", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:AddLoop("m_ambience_pipeflow2_pos6", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipeflow2.wav",
        volume = 0.75,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 6, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_electrichum1_pos7", {
        sounds = "bms_ambience/machine_ambience/m_ambience_electrichum1.wav",
        volume = 0.45,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 7, soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a0b.hw2.util_pos0-1", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("m_ambience_lc17_pos0", {
        sounds = "bms_ambience/machine_ambience/m_ambience_lc17.wav",
        volume = 0.75,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_lc17a_pos1", {
        sounds = "bms_ambience/machine_ambience/m_ambience_lc17a.wav",
        volume = 0.7,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a0b.hw2.util_pos2-3", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:AddLoop("o_ambience_disaster_fire2_pos2", {
        sounds = "bms_ambience/object_ambience/o_ambience_disaster_fire2.wav",
        volume = 0.45,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("o_ambience_disaster_fire8_pos3", {
        sounds = "bms_ambience/object_ambience/o_ambience_disaster_fire8.wav",
        volume = 0.45,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 3, soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a0b.ctrl.util_pos0", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("m_ambience_vent2_pos0", {
        sounds = "bms_ambience/machine_ambience/m_ambience_vent2.wav",
        volume = 0.3,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 70 },
        preload = true,
    })
end)

ax.scapes:Register("c1a0b.ctrl.pos4blendscape", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("r_ambience_lab1a_pos4", {
        sounds = ")BMS_ambience/room_ambience/r_ambience_lab1a.wav",
        volume = 1.0,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 4, soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a0b.tcf.util_pos0-1", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("m_ambience_electrichum1_pos1", {
        sounds = "bms_ambience/machine_ambience/m_ambience_electrichum1.wav",
        volume = 0.05,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("r_ambience_fan1_pos0", {
        sounds = "bms_ambience/room_ambience/r_ambience_fan1.wav",
        volume = 0.15,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a0b.hallway3", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:2")
    builder:AddSubScape("c1a0b.hallway.base")
    builder:AddSubScape("c1a0b.h3.util_pos0-3")
    builder:AddSubScape("c1a0b.h3.util_pos4-7")
end)

ax.scapes:Register("c1a0b.hallway2_2", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:2")
    builder:AddSubScape("c1a0b.hallway.base")
    builder:AddSubScape("c1a0b.hw2.util_pos0-1")
    builder:AddSubScape("c1a0b.ionroom.util_pos4-5")
end)

ax.scapes:Register("c1a0b.hallway2", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:2")
    builder:AddSubScape("c1a0b.hallway.base")
    builder:AddSubScape("c1a0b.hw2.util_pos0-1")
    builder:AddSubScape("c1a0b.ionroom.util_pos4-5")
    builder:AddSubScape("c1a0b.ionroom.util_pos6-7")
end)

ax.scapes:Register("c1a0b.ionroom", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:2")
    builder:AddSubScape("c1a0b.hallway.base")
    builder:AddSubScape("c1a0b.hw2.util_pos0-1")
    builder:AddSubScape("c1a0b.ionroom.util_pos4-5")
    builder:AddSubScape("c1a0b.ionroom.util_pos6-7")
end)

ax.scapes:Register("c1a0b.ionroom_s2", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:2")
    builder:AddSubScape("c1a0b.hallway.base")
    builder:AddSubScape("c1a0b.ctrl.util_pos0")
    builder:AddSubScape("c1a0b.ctrl.pos4blendscape")
    builder:AddSubScape("c1a0b.ionroom.util_pos4-5")
    builder:AddSubScape("c1a0b.ionroom.util_pos6-7")
    builder:AddSubScape("c1a0.computers", {
        volumeMultiplier = 0.25,
    })
end)

ax.scapes:Register("c1a0b.contolroom", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:2")
    builder:AddSubScape("c1a0b.contolroom.base")
    builder:AddSubScape("c1a0.computers", {
        volumeMultiplier = 0.35,
    })
    builder:AddSubScape("c1a0b.ctrl.util_pos0")
end)

ax.scapes:Register("c1a0b.tuberoom", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:2")
    builder:AddSubScape("c1a0b.hallway.base")
    builder:AddSubScape("c1a0b.ctrl.pos4blendscape")
    builder:AddSubScape("c1a0b.t1.util_pos1-3")
    builder:AddSubScape("c1a0b.h1.util_pos5")
end)

ax.scapes:Register("c1a0b.tuberoom_v2", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:2")
    builder:AddSubScape("c1a0b.hallway.base")
    builder:AddSubScape("c1a0b.t1.util_pos1-3")
    builder:AddSubScape("c1a0b.h1.util_pos5")
end)

ax.scapes:Register("c1a0b.hallway1", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:2")
    builder:AddSubScape("c1a0b.hallway.base")
    builder:AddSubScape("c1a0b.tcf.util_pos0-1", {
        volumeMultiplier = 0.65,
    })
    builder:AddSubScape("c1a0b.h1.util_pos5")
end)

ax.scapes:Register("c1a0b.tcfoyer", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:2")
    builder:AddSubScape("c1a0b.hallway.base")
    builder:AddSubScape("c1a0b.tcf.util_pos0-1")
end)

ax.scapes:Register("c1a0b.tcfoyer_v2", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:2")
    builder:AddSubScape("c1a0b.hallway.base")
    builder:AddSubScape("c1a0b.tcf.util_pos0-1")
    builder:AddLoop("r_ambience_large8_pos3", {
        sounds = ")BMS_ambience/room_ambience/r_ambience_large8.wav",
        volume = 1.0,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 3, soundLevel = 80 },
        preload = true,
    })
end)

ax.scapes:Register("c1a0b.testchamber", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:10")
    builder:AddSubScape("c1a0b.tcf.util_pos0-1", {
        volumeMultiplier = 0.65,
    })
    builder:AddLoop("r_ambience_large8", {
        sounds = "BMS_ambience/room_ambience/r_ambience_large8.wav",
        volume = 1.0,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a0b.xenshowcase", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:10")
    builder:AddLoop("r_ambience_xen3", {
        sounds = "BMS_ambience/room_ambience/r_ambience_xen3.wav",
        volume = 0.9,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("r_ambience_xen5", {
        sounds = "bms_ambience/room_ambience/r_ambience_xen5.wav",
        volume = 0.3,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)
