-- Auto-generated by tools/generate_scapes_from_soundscapes.py
-- Source: C:/Program Files (x86)/Steam/steamapps/common/GarrysMod/garrysmod/addons/rp_black_mesa_facility/scripts/soundscapes_bs_c0.txt
-- Scapes emitted: 14


ax.scapes:Register("tramride_outdoor", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:21")
    builder:AddLoop("r_ambience_wind3", {
        sounds = "bms_ambience/room_ambience/r_ambience_wind3.wav",
        volume = 0.6,
        pitch = 90.0,
        spatial = { mode = "ambient", soundLevel = 120 },
        preload = true,
    })
    builder:AddLoop("m_ambience_misc10_pos0", {
        sounds = "bms_ambience/machine_ambience/m_ambience_misc10.wav",
        volume = 0.6,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipeflow1_pos1", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipeflow1.wav",
        volume = 0.7,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipeflow1a_pos2", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipeflow1a.wav",
        volume = 0.7,
        pitch = 90.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_misc10a_pos3", {
        sounds = "bms_ambience/machine_ambience/m_ambience_misc10a.wav",
        volume = 0.8,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 3, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_electrical1_pos4", {
        sounds = "bms_ambience/machine_ambience/m_ambience_electrical1.wav",
        volume = 0.8,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 4, soundLevel = 80 },
        preload = true,
    })
end)

ax.scapes:Register("tramride_shaft", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:18")
    builder:AddLoop("r_ambience_large4", {
        sounds = "bms_ambience/room_ambience/r_ambience_large4.wav",
        volume = 0.6,
        pitch = 90.0,
        spatial = { mode = "ambient", soundLevel = 120 },
        preload = true,
    })
    builder:AddLoop("fan7_pos0", {
        sounds = "bms_objects/fans/fan7.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("fan7a_pos1", {
        sounds = "bms_objects/fans/fan7a.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("tramride_cave", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:24")
    builder:AddLoop("r_ambience_large8", {
        sounds = "bms_ambience/room_ambience/r_ambience_large8.wav",
        volume = 0.6,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 110 },
        preload = true,
    })
    builder:AddLoop("m_ambience_motor2_pos0", {
        sounds = "bms_ambience/machine_ambience/m_ambience_motor2.wav",
        volume = 0.6,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("m_ambience_ind5_pos1", {
        sounds = "bms_ambience/machine_ambience/m_ambience_ind5.wav",
        volume = 0.4,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("r_ambience_water18_pos2", {
        sounds = "bms_ambience/room_ambience/r_ambience_water18.wav",
        volume = 0.8,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("r_ambience_water15_pos3", {
        sounds = "bms_ambience/room_ambience/r_ambience_water15.wav",
        volume = 0.8,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 3, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("r_ambience_water15a_pos4", {
        sounds = "bms_ambience/room_ambience/r_ambience_water15a.wav",
        volume = 0.7,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 4, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("m_ambience_ind32_pos5", {
        sounds = "bms_ambience/machine_ambience/m_ambience_ind32.wav",
        volume = 0.6,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 5, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("fan6_pos6", {
        sounds = "bms_objects/fans/fan6.wav",
        volume = 0.4,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 6, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipe2_pos7", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipe2.wav",
        volume = 0.3,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 7, soundLevel = 65 },
        preload = true,
    })
end)

ax.scapes:Register("tramride_tramdoor", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:18")
    builder:AddLoop("r_ambience_large9a", {
        sounds = "bms_ambience/room_ambience/r_ambience_large9a.wav",
        volume = 0.7,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 120 },
        preload = true,
    })
    builder:AddLoop("r_ambience_med11", {
        sounds = "bms_ambience/room_ambience/r_ambience_med11.wav",
        volume = 0.4,
        pitch = 90.0,
        spatial = { mode = "ambient", soundLevel = 100 },
        preload = true,
    })
    builder:AddLoop("m_ambience_energy3_pos0", {
        sounds = "bms_ambience/machine_ambience/m_ambience_energy3.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("city_ventpump_loop1_pos1", {
        sounds = "ambient/machines/city_ventpump_loop1.wav",
        volume = 0.8,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 65 },
        preload = true,
    })
    builder:AddLoop("r_ambience_water5_pos2", {
        sounds = "bms_ambience/room_ambience/r_ambience_water5.wav",
        volume = 0.3,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("m_ambience_motor1_pos3", {
        sounds = "bms_ambience/machine_ambience/m_ambience_motor1.wav",
        volume = 0.3,
        pitch = 115.0,
        spatial = { mode = "positional", positionKey = 3, soundLevel = 70 },
        preload = true,
    })
end)

ax.scapes:Register("tramride_tunnelA", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:6")
    builder:AddLoop("r_ambience_med12", {
        sounds = "bms_ambience/room_ambience/r_ambience_med12.wav",
        volume = 0.6,
        pitch = 90.0,
        spatial = { mode = "ambient", soundLevel = 120 },
        preload = true,
    })
    builder:AddLoop("fan2_pos0", {
        sounds = "bms_objects/fans/fan2.wav",
        volume = 0.6,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipeflow1_pos1", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipeflow1.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipeflow1a_pos2", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipeflow1a.wav",
        volume = 0.7,
        pitch = 90.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_electrichum1_pos3", {
        sounds = "bms_ambience/machine_ambience/m_ambience_electrichum1.wav",
        volume = 0.6,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 3, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("m_ambience_motor2_pos4", {
        sounds = "bms_ambience/machine_ambience/m_ambience_motor2.wav",
        volume = 0.8,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 4, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("m_ambience_electrical1_pos5", {
        sounds = "bms_ambience/machine_ambience/m_ambience_electrical1.wav",
        volume = 0.7,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 5, soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("tramride_tunnelB", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:7")
    builder:AddLoop("r_ambience_large8", {
        sounds = "bms_ambience/room_ambience/r_ambience_large8.wav",
        volume = 0.6,
        pitch = 90.0,
        spatial = { mode = "ambient", soundLevel = 120 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipeflow1_pos0", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipeflow1.wav",
        volume = 0.6,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipeflow1a_pos1", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipeflow1a.wav",
        volume = 0.5,
        pitch = 80.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipeflow1b_pos2", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipeflow1b.wav",
        volume = 0.7,
        pitch = 110.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_motor3_pos3", {
        sounds = "bms_ambience/machine_ambience/m_ambience_motor3.wav",
        volume = 0.7,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 3, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("m_ambience_misc9_pos4", {
        sounds = "bms_ambience/machine_ambience/m_ambience_misc9.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 4, soundLevel = 70 },
        preload = true,
    })
end)

ax.scapes:Register("tramride_tunnelC", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:19")
    builder:AddLoop("r_ambience_med3", {
        sounds = "bms_ambience/room_ambience/r_ambience_med3.wav",
        volume = 0.4,
        pitch = 110.0,
        spatial = { mode = "ambient", soundLevel = 120 },
        preload = true,
    })
    builder:AddLoop("r_ambience_lab2", {
        sounds = "bms_ambience/room_ambience/r_ambience_lab2.wav",
        volume = 0.8,
        pitch = 90.0,
        spatial = { mode = "ambient", soundLevel = 110 },
        preload = true,
    })
    builder:AddLoop("r_ambience_ppl1", {
        sounds = "bms_ambience/room_ambience/r_ambience_ppl1.wav",
        volume = 0.4,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 90 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipe2_pos0", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipe2.wav",
        volume = 0.6,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 60 },
        preload = true,
    })
    builder:AddLoop("m_ambience_energy5_pos1", {
        sounds = "bms_ambience/machine_ambience/m_ambience_energy5.wav",
        volume = 0.7,
        pitch = 110.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("r_ambience_ppl2_pos2", {
        sounds = "bms_ambience/room_ambience/r_ambience_ppl2.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 60 },
        preload = true,
    })
end)

ax.scapes:Register("tramride_cafeteria", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:21")
    builder:AddLoop("r_ambience_wind3", {
        sounds = "bms_ambience/room_ambience/r_ambience_wind3.wav",
        volume = 0.8,
        pitch = 110.0,
        spatial = { mode = "ambient", soundLevel = 120 },
        preload = true,
    })
    builder:AddLoop("r_ambience_ppl2", {
        sounds = "bms_ambience/room_ambience/r_ambience_ppl2.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 100 },
        preload = true,
    })
end)

ax.scapes:Register("tramride_checkpoint", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:19")
    builder:AddLoop("r_ambience_med10", {
        sounds = "bms_ambience/room_ambience/r_ambience_med10.wav",
        volume = 0.4,
        pitch = 110.0,
        spatial = { mode = "ambient", soundLevel = 120 },
        preload = true,
    })
    builder:AddLoop("r_ambience_lab1", {
        sounds = "bms_ambience/room_ambience/r_ambience_lab1.wav",
        volume = 0.6,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 110 },
        preload = true,
    })
    builder:AddLoop("hum2_pos0", {
        sounds = "bms_objects/hum/hum2.wav",
        volume = 0.7,
        pitch = 90.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("fan2_pos1", {
        sounds = "bms_objects/fans/fan2.wav",
        volume = 0.7,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("r_ambience_med3_pos2", {
        sounds = "bms_ambience/room_ambience/r_ambience_med3.wav",
        volume = 0.7,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 65 },
        preload = true,
    })
    builder:AddLoop("m_ambience_electrical2slow_pos3", {
        sounds = "bms_ambience/machine_ambience/m_ambience_electrical2slow.wav",
        volume = 0.7,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 3, soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("tramride_transfer", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:19")
    builder:AddLoop("r_ambience_elev_shaft2", {
        sounds = "bms_ambience/room_ambience/r_ambience_elev_shaft2.wav",
        volume = 0.7,
        pitch = 90.0,
        spatial = { mode = "ambient", soundLevel = 120 },
        preload = true,
    })
    builder:AddLoop("r_ambience_wind1", {
        sounds = "bms_ambience/room_ambience/r_ambience_wind1.wav",
        volume = 0.3,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 110 },
        preload = true,
    })
    builder:AddLoop("r_ambience_med13_pos0", {
        sounds = "bms_ambience/room_ambience/r_ambience_med13.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 85 },
        preload = true,
    })
    builder:AddLoop("r_ambience_med14_pos1", {
        sounds = "bms_ambience/room_ambience/r_ambience_med14.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 80 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipe3_pos2", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipe3.wav",
        volume = 0.7,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 65 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipe3a_pos3", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipe3a.wav",
        volume = 0.7,
        pitch = 120.0,
        spatial = { mode = "positional", positionKey = 3, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("m_ambience_misc8_pos4", {
        sounds = "bms_ambience/machine_ambience/m_ambience_misc8.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 4, soundLevel = 70 },
        preload = true,
    })
end)

ax.scapes:Register("tramride_C_line", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:19")
    builder:AddLoop("r_ambience_large8", {
        sounds = "bms_ambience/room_ambience/r_ambience_large8.wav",
        volume = 0.7,
        pitch = 110.0,
        spatial = { mode = "ambient", soundLevel = 120 },
        preload = true,
    })
    builder:AddLoop("r_ambience_wind1", {
        sounds = "bms_ambience/room_ambience/r_ambience_wind1.wav",
        volume = 0.3,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 100 },
        preload = true,
    })
    builder:AddLoop("r_ambience_med3_pos0", {
        sounds = "bms_ambience/room_ambience/r_ambience_med3.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 80 },
        preload = true,
    })
    builder:AddLoop("r_ambience_med3a_pos1", {
        sounds = "bms_ambience/room_ambience/r_ambience_med3a.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 80 },
        preload = true,
    })
    builder:AddLoop("transformer_loop_pos2", {
        sounds = "ambient/machines/transformer_loop.wav",
        volume = 0.4,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipe3_pos3", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipe3.wav",
        volume = 0.7,
        pitch = 110.0,
        spatial = { mode = "positional", positionKey = 3, soundLevel = 70 },
        preload = true,
    })
end)

ax.scapes:Register("arrival_checkpoint", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:19")
    builder:AddLoop("r_ambience_med4", {
        sounds = "bms_ambience/room_ambience/r_ambience_med4.wav",
        volume = 0.7,
        pitch = 110.0,
        spatial = { mode = "ambient", soundLevel = 120 },
        preload = true,
    })
    builder:AddLoop("r_ambience_med9", {
        sounds = "bms_ambience/room_ambience/r_ambience_med9.wav",
        volume = 0.3,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 90 },
        preload = true,
    })
    builder:AddLoop("r_ambience_med8_pos0", {
        sounds = "bms_ambience/room_ambience/r_ambience_med8.wav",
        volume = 0.4,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 80 },
        preload = true,
    })
    builder:AddLoop("r_ambience_med3a_pos1", {
        sounds = "bms_ambience/room_ambience/r_ambience_med3a.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 60 },
        preload = true,
    })
    builder:AddLoop("m_ambience_comp3_pos2", {
        sounds = "bms_ambience/machine_ambience/m_ambience_comp3.wav",
        volume = 0.2,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_electrichum1_pos3", {
        sounds = "bms_ambience/machine_ambience/m_ambience_electrichum1.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 3, soundLevel = 60 },
        preload = true,
    })
end)

ax.scapes:Register("arrival_hall", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:17")
    builder:AddLoop("r_ambience_lab1", {
        sounds = "bms_ambience/room_ambience/r_ambience_lab1.wav",
        volume = 0.4,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 120 },
        preload = true,
    })
    builder:AddLoop("m_ambience_comp1_pos0", {
        sounds = "bms_ambience/machine_ambience/m_ambience_comp1.wav",
        volume = 0.3,
        pitch = 90.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 65 },
        preload = true,
    })
    builder:AddLoop("m_ambience_vent1_pos1", {
        sounds = "bms_ambience/machine_ambience/m_ambience_vent1.wav",
        volume = 0.3,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 70 },
        preload = true,
    })
end)

ax.scapes:Register("arrival_platform", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:19")
    builder:AddLoop("r_ambience_med4", {
        sounds = "bms_ambience/room_ambience/r_ambience_med4.wav",
        volume = 0.7,
        pitch = 110.0,
        spatial = { mode = "ambient", soundLevel = 120 },
        preload = true,
    })
    builder:AddLoop("r_ambience_med9", {
        sounds = "bms_ambience/room_ambience/r_ambience_med9.wav",
        volume = 0.3,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 90 },
        preload = true,
    })
    builder:AddLoop("r_ambience_med13_pos0", {
        sounds = "bms_ambience/room_ambience/r_ambience_med13.wav",
        volume = 0.7,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("vending_hum_pos1", {
        sounds = "bms_objects/vmachine/vending_hum.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 65 },
        preload = true,
    })
    builder:AddLoop("m_ambience_comp1_pos2", {
        sounds = "bms_ambience/machine_ambience/m_ambience_comp1.wav",
        volume = 0.3,
        pitch = 85.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 65 },
        preload = true,
    })
end)
