-- Auto-generated by tools/generate_scapes_from_soundscapes.py
-- Source: C:/Program Files (x86)/Steam/steamapps/common/GarrysMod/garrysmod/addons/rp_black_mesa_facility/scripts/soundscapes_c0a0.txt
-- Scapes emitted: 54


ax.scapes:Register("ib.a.huge_tunnels", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:7")
    builder:AddSubScape("ib.huge_tunnel.base")
end)

ax.scapes:Register("ib.station.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("r_ambience_station1", {
        sounds = "bms_ambience/room_ambience/r_ambience_station1.wav",
        volume = 0.7,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("r_ambience_ppl1", {
        sounds = "bms_ambience/room_ambience/r_ambience_ppl1.wav",
        volume = 0.6,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("soundscape_station1", {
        sounds = "bms_ambience/soundscape/soundscape_station1.wav",
        volume = 0.6,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("ib.area9hub.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:7")
    builder:AddLoop("r_ambience_large6", {
        sounds = "bms_ambience/room_ambience/r_ambience_large6.wav",
        volume = 1.0,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("ib.huge_tunnel.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:7")
    builder:AddLoop("r_ambience_large6", {
        sounds = "bms_ambience/room_ambience/r_ambience_large6.wav",
        volume = 1.0,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("ib.tunnel_small.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:5")
    builder:AddLoop("r_ambience_small3", {
        sounds = "bms_ambience/room_ambience/r_ambience_small3.wav",
        volume = 0.9,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("ib.factoryarea.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:10")
    builder:AddLoop("r_ambience_large5", {
        sounds = "bms_ambience/room_ambience/r_ambience_large5.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("r_ambience_tramIndustrial1", {
        sounds = "bms_ambience/room_ambience/r_ambience_tramIndustrial1.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("ib.outsidevista.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:1")
    builder:AddLoop("r_ambience_desertday1", {
        sounds = "bms_ambience/room_ambience/r_ambience_desertday1.wav",
        volume = 0.6,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("r_ambience_wind2", {
        sounds = "bms_ambience/room_ambience/r_ambience_wind2.wav",
        volume = 0.3,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("ib.cave.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:24")
    builder:AddLoop("r_ambience_wind1", {
        sounds = "bms_ambience/room_ambience/r_ambience_wind1.wav",
        volume = 0.6,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("r_ambience_wind5", {
        sounds = "bms_ambience/room_ambience/r_ambience_wind5.wav",
        volume = 0.6,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("ib.tunnels_door.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:9")
    builder:AddLoop("r_ambience_large4", {
        sounds = "bms_ambience/room_ambience/r_ambience_large4.wav",
        volume = 0.8,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("ib.bridge_room.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:10")
    builder:AddLoop("r_ambience_large2", {
        sounds = "bms_ambience/room_ambience/r_ambience_large2.wav",
        volume = 0.8,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("ib.reactor_room.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:10")
    builder:AddLoop("r_ambience_large6", {
        sounds = "bms_ambience/room_ambience/r_ambience_large6.wav",
        volume = 0.8,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("ib.vat_room.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:19")
    builder:AddLoop("r_ambience_industrial5", {
        sounds = "bms_ambience/room_ambience/r_ambience_industrial5.wav",
        volume = 0.8,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("ib.am.catwalk.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:10")
    builder:AddLoop("r_ambience_large8", {
        sounds = "bms_ambience/room_ambience/r_ambience_large8.wav",
        volume = 0.8,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("a_t1s1.util_pos0-1", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("m_ambience_electrichum1_pos0", {
        sounds = "bms_ambience/machine_ambience/m_ambience_electrichum1.wav",
        volume = 0.3,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_electrichum1a_pos1", {
        sounds = "bms_ambience/machine_ambience/m_ambience_electrichum1a.wav",
        volume = 0.3,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("a_t1s2.util_pos6-7", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("m_ambience_electrichum1b_pos6", {
        sounds = "bms_ambience/machine_ambience/m_ambience_electrichum1b.wav",
        volume = 0.3,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 6, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipe4_pos7", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipe4.wav",
        volume = 0.35,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 7, soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("a_t1s3.util_pos0-1", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("m_ambience_electrichum1_pos0", {
        sounds = "bms_ambience/machine_ambience/m_ambience_electrichum1.wav",
        volume = 0.3,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_electrichum1a_pos1", {
        sounds = "bms_ambience/machine_ambience/m_ambience_electrichum1a.wav",
        volume = 0.3,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("a_t1s3.util_pos2-3", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("m_ambience_comp1_pos2", {
        sounds = "bms_ambience/machine_ambience/m_ambience_comp1.wav",
        volume = 0.3,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("equipment_beep_loop1_pos3", {
        sounds = "ambient/levels/labs/equipment_beep_loop1.wav",
        volume = 0.23,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 3, soundLevel = 70 },
        preload = true,
    })
end)

ax.scapes:Register("a_t1s3.util_pos5only", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("m_ambience_pipe1_pos5", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipe1.wav",
        volume = 0.75,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 5, soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("ib.a.station_start", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:10")
    builder:AddSubScape("ib.station.base")
    builder:AddSubScape("a_t1s1.util_pos0-1", {
        volumeMultiplier = 0.85,
    })
end)

ax.scapes:Register("ib.a.tunnel1_section1", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:7")
    builder:AddSubScape("ib.tunnel_small.base")
    builder:AddSubScape("a_t1s1.util_pos0-1")
end)

ax.scapes:Register("ib.a.tunnel1_section2", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:7")
    builder:AddSubScape("ib.tunnel_small.base")
    builder:AddSubScape("a_t1s2.util_pos6-7")
    builder:AddSubScape("a_t1s3.util_pos5only")
end)

ax.scapes:Register("ib.a.tunnel1_section3", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:7")
    builder:AddSubScape("ib.tunnel_small.base")
    builder:AddSubScape("a_t1s3.util_pos0-1")
    builder:AddSubScape("a_t1s3.util_pos2-3")
    builder:AddSubScape("a_t1s3.util_pos5only")
end)

ax.scapes:Register("ib.a.area9hub", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:7")
    builder:AddSubScape("ib.area9hub.base")
end)

ax.scapes:Register("ib.a.tunnel2", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:5")
    builder:AddSubScape("ib.tunnel_small.base")
end)

ax.scapes:Register("b_t1.util_pos0only", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("m_ambience_pipe4a_pos0", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipe4a.wav",
        volume = 0.2,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("b_t2.util_pos0-1", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("m_ambience_electrical1_pos0", {
        sounds = "bms_ambience/machine_ambience/m_ambience_electrical1.wav",
        volume = 0.45,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_misc10_pos1", {
        sounds = "bms_ambience/machine_ambience/m_ambience_misc10.wav",
        volume = 0.4,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("b_fct.util_pos2-3", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("m_ambience_electrichum1_pos2", {
        sounds = "bms_ambience/machine_ambience/m_ambience_electrichum1.wav",
        volume = 0.45,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipe4_pos3", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipe4.wav",
        volume = 0.4,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 3, soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("b_t3.util_pos6-7", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("m_ambience_pipeflow1_pos6", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipeflow1.wav",
        volume = 0.4,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 6, soundLevel = 80 },
        preload = true,
    })
    builder:AddLoop("m_ambience_electrichum1b_pos7", {
        sounds = "bms_ambience/machine_ambience/m_ambience_electrichum1b.wav",
        volume = 0.2,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 7, soundLevel = 70 },
        preload = true,
    })
end)

ax.scapes:Register("b_vsta1.util_pos7only", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:AddLoop("m_ambience_electrichum1a_pos7", {
        sounds = "bms_ambience/machine_ambience/m_ambience_electrichum1a.wav",
        volume = 0.35,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 7, soundLevel = 70 },
        preload = true,
    })
end)

ax.scapes:Register("b_cave1.util_pos0-1", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("steam_loop1_pos0", {
        sounds = "ambient/gas/steam_loop1.wav",
        volume = 0.25,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipe4_pos1", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipe4.wav",
        volume = 0.25,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("b_tdoors.util_pos0-1", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("m_ambience_pipeflow1_pos0", {
        sounds = "BMS_ambience/machine_ambience/m_ambience_pipeflow1.wav",
        volume = 0.75,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("vending_hum_pos1", {
        sounds = "bms_objects/vmachine/vending_hum.wav",
        volume = 0.55,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 85 },
        preload = true,
    })
end)

ax.scapes:Register("ib.b.tunnel1", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:7")
    builder:AddSubScape("ib.tunnel_small.base")
    builder:AddSubScape("b_t1.util_pos0only")
end)

ax.scapes:Register("ib.b.factoryarea_s1", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:10")
    builder:AddSubScape("ib.factoryarea.base")
end)

ax.scapes:Register("ib.b.tunnel2", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:7")
    builder:AddSubScape("ib.tunnel_small.base")
    builder:AddSubScape("b_t2.util_pos0-1")
end)

ax.scapes:Register("ib.b.factoryarea_s2", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:10")
    builder:AddSubScape("ib.factoryarea.base")
    builder:AddSubScape("b_fct.util_pos2-3")
end)

ax.scapes:Register("ib.b.tunnel3", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:7")
    builder:AddSubScape("ib.tunnel_small.base")
    builder:AddSubScape("b_t3.util_pos6-7")
    builder:AddSubScape("b_fct.util_pos2-3")
end)

ax.scapes:Register("ib.b.outsidevista1", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:1")
    builder:AddSubScape("ib.outsidevista.base")
    builder:AddSubScape("b_vsta1.util_pos7only")
    builder:AddSubScape("b_cave1.util_pos0-1")
end)

ax.scapes:Register("ib.b.cave1", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:24")
    builder:AddSubScape("ib.cave.base")
    builder:AddSubScape("b_cave1.util_pos0-1")
end)

ax.scapes:Register("ib.b.outsidevista2", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:1")
    builder:AddSubScape("ib.outsidevista.base")
end)

ax.scapes:Register("ib.b.cave2", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:24")
    builder:AddSubScape("ib.cave.base")
    builder:AddSubScape("b_tdoors.util_pos0-1")
end)

ax.scapes:Register("ib.b.tunnels_door", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:9")
    builder:AddSubScape("ib.tunnels_door.base")
    builder:AddSubScape("b_tdoors.util_pos0-1")
    builder:AddSubScape("c_t1.util_pos6-7")
end)

ax.scapes:Register("ib.b.tunnels_door2", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:9")
    builder:AddSubScape("ib.tunnels_door.base")
end)

ax.scapes:Register("c_t1.util_pos6-7", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("m_ambience_electrichum1_pos6", {
        sounds = "bms_ambience/machine_ambience/m_ambience_electrichum1.wav",
        volume = 0.2,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 6, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipeflow1_pos7", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipeflow1.wav",
        volume = 0.2,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 7, soundLevel = 70 },
        preload = true,
    })
end)

ax.scapes:Register("c_t1.util_pos3-5", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("m_ambience_pipe5_pos3", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipe5.wav",
        volume = 0.22,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 3, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipe4_pos4", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipe4.wav",
        volume = 0.22,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 4, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipe4a_pos5", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipe4a.wav",
        volume = 0.22,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 5, soundLevel = 70 },
        preload = true,
    })
end)

ax.scapes:Register("c_t3.util_pos5-7", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("m_ambience_pipe4a_pos5", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipe4a.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 5, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipe3_pos6", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipe3.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 6, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("fan4_pos7", {
        sounds = "bms_objects/fans/fan4.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 7, soundLevel = 80 },
        preload = true,
    })
end)

ax.scapes:Register("ib.c.tunnels_door", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:9")
    builder:AddSubScape("ib.tunnels_door.base")
end)

ax.scapes:Register("ib.c.tunnel1", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:5")
    builder:AddSubScape("ib.tunnel_small.base")
    builder:AddSubScape("c_t1.util_pos6-7")
    builder:AddSubScape("c_t1.util_pos3-5")
end)

ax.scapes:Register("ib.c.reactor_room", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:10")
    builder:AddSubScape("ib.reactor_room.base")
end)

ax.scapes:Register("ib.c.tunnel2", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:5")
    builder:AddSubScape("ib.tunnel_small.base")
end)

ax.scapes:Register("ib.c.bridge_room", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:10")
    builder:AddSubScape("ib.bridge_room.base")
end)

ax.scapes:Register("ib.c.tunnel3", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:5")
    builder:AddSubScape("ib.tunnel_small.base")
    builder:AddSubScape("c_t3.util_pos5-7")
end)

ax.scapes:Register("ib.c.vat_room", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:19")
    builder:AddSubScape("ib.vat_room.base")
end)

ax.scapes:Register("ib.c.tunnel4", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:5")
    builder:AddSubScape("ib.tunnel_small.base")
end)

ax.scapes:Register("ib.am_entrance", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:10")
    builder:AddSubScape("ib.am.catwalk.base")
end)
