-- Auto-generated by tools/generate_scapes_from_soundscapes.py
-- Source: C:/Program Files (x86)/Steam/steamapps/common/GarrysMod/garrysmod/addons/rp_black_mesa_facility/scripts/soundscapes_c1a1.txt
-- Scapes emitted: 86


ax.scapes:Register("c1a1c.hallway.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:AddLoop("r_ambience_large2", {
        sounds = "BMS_ambience/room_ambience/r_ambience_large2.wav",
        volume = 0.4,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("r_ambience_med9", {
        sounds = "BMS_ambience/room_ambience/r_ambience_med9.wav",
        volume = 0.3,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1c.hallway1.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:AddLoop("r_ambience_disaster_rumble1", {
        sounds = "BMS_ambience/room_ambience/r_ambience_disaster_rumble1.wav",
        volume = 0.4,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1c.frozenlab1.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:AddLoop("r_ambience_med6", {
        sounds = "BMS_ambience/room_ambience/r_ambience_med6.wav",
        volume = 0.7,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("r_ambience_disaster_rumble6", {
        sounds = "BMS_ambience/room_ambience/r_ambience_disaster_rumble6.wav",
        volume = 0.3,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1c.warehouse.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:AddLoop("r_ambience_med8", {
        sounds = "bms_ambience/room_ambience/r_ambience_med8.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("r_ambience_eleshaft1", {
        sounds = "bms_ambience/room_ambience/r_ambience_eleshaft1.wav",
        volume = 0.15,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1c.hallway1.util_pos0-2", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("alarm5_pos0", {
        sounds = "bms_objects/alarms/alarm5.wav",
        volume = 0.6,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 85 },
        preload = true,
    })
    builder:AddLoop("alarm5a_pos1", {
        sounds = "bms_objects/alarms/alarm5a.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 85 },
        preload = true,
    })
    builder:AddLoop("o_ambience_disaster_fire5_pos2", {
        sounds = "bms_ambience/object_ambience/o_ambience_disaster_fire5.wav",
        volume = 0.8,
        pitch = 90.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 85 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1c.hallway1.util_pos3-4", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:AddLoop("white_noise_pos3", {
        sounds = "bms_objects/white_noise.wav",
        volume = 0.8,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 3, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_misc7_pos4", {
        sounds = "bms_ambience/machine_ambience/m_ambience_misc7.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 4, soundLevel = 70 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1c.mt1.util_pos3_6_7", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:AddLoop("o_ambience_disaster_fire4_pos3", {
        sounds = "bms_ambience/object_ambience/o_ambience_disaster_fire4.wav",
        volume = 0.6,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 3, soundLevel = 80 },
        preload = true,
    })
    builder:AddLoop("m_ambience_misc7_pos6", {
        sounds = "bms_ambience/machine_ambience/m_ambience_misc7.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 6, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("alarm5b_pos7", {
        sounds = "bms_objects/alarms/alarm5b.wav",
        volume = 0.6,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 7, soundLevel = 80 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1c.elevatorshaft.util_pos3_6_7", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:AddLoop("o_ambience_disaster_fire4_pos3", {
        sounds = "bms_ambience/object_ambience/o_ambience_disaster_fire4.wav",
        volume = 0.6,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 3, soundLevel = 80 },
        preload = true,
    })
    builder:AddLoop("r_ambience_water4_pos6", {
        sounds = "bms_ambience/room_ambience/r_ambience_water4.wav",
        volume = 0.8,
        pitch = 97.0,
        spatial = { mode = "positional", positionKey = 6, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("alarm5b_pos7", {
        sounds = "bms_objects/alarms/alarm5b.wav",
        volume = 0.3,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 7, soundLevel = 80 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1c.warehouse.util_pos4-7", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("m_ambience_electrichum1_pos4", {
        sounds = "bms_ambience/machine_ambience/m_ambience_electrichum1.wav",
        volume = 0.2,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 4, soundLevel = 65 },
        preload = true,
    })
    builder:AddLoop("hum2_pos5", {
        sounds = "bms_objects/hum/hum2.wav",
        volume = 0.6,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 5, soundLevel = 65 },
        preload = true,
    })
    builder:AddLoop("r_ambience_water4_pos6", {
        sounds = "bms_ambience/room_ambience/r_ambience_water4.wav",
        volume = 0.8,
        pitch = 97.0,
        spatial = { mode = "positional", positionKey = 6, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipe1_pos7", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipe1.wav",
        volume = 0.4,
        pitch = 97.0,
        spatial = { mode = "positional", positionKey = 7, soundLevel = 65 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1c.util.hallway2", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("m_ambience_comp1_pos0", {
        sounds = "bms_ambience/machine_ambience/m_ambience_comp1.wav",
        volume = 0.6,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("m_ambience_comp2_pos1", {
        sounds = "bms_ambience/machine_ambience/m_ambience_comp2.wav",
        volume = 0.6,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("hum1_pos2", {
        sounds = "bms_objects/hum/hum1.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipe3_pos3", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipe3.wav",
        volume = 0.35,
        pitch = 80.0,
        spatial = { mode = "positional", positionKey = 3, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_watercontainer_pos4", {
        sounds = "BMS_ambience/machine_ambience/m_ambience_watercontainer.wav",
        volume = 0.4,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 4, soundLevel = 80 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipeflow1_pos5", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipeflow1.wav",
        volume = 0.5,
        pitch = 150.0,
        spatial = { mode = "positional", positionKey = 5, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_watercontainer2_pos6", {
        sounds = "BMS_ambience/machine_ambience/m_ambience_watercontainer2.wav",
        volume = 0.4,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 6, soundLevel = 80 },
        preload = true,
    })
    builder:AddLoop("waterleak_loop1_pos7", {
        sounds = "ambient/levels/canals/waterleak_loop1.wav",
        volume = 0.3,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 7, soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1c.util.hallway3", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("m_ambience_pipe3_pos0", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipe3.wav",
        volume = 0.55,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 80 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipe2_pos1", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipe2.wav",
        volume = 0.45,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 85 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipe2a_pos2", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipe2a.wav",
        volume = 0.45,
        pitch = 50.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 80 },
        preload = true,
    })
    builder:AddLoop("m_ambience_comp2_pos3", {
        sounds = "bms_ambience/machine_ambience/m_ambience_comp2.wav",
        volume = 0.28,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 3, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("waterleak_loop1_pos5", {
        sounds = "ambient/levels/canals/waterleak_loop1.wav",
        volume = 0.5,
        pitch = 80.0,
        spatial = { mode = "positional", positionKey = 5, soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1c.util.hallway4", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("m_ambience_pipe2b_pos4", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipe2b.wav",
        volume = 0.25,
        pitch = 110.0,
        spatial = { mode = "positional", positionKey = 4, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("fan6_pos6", {
        sounds = "bms_objects/fans/fan6.wav",
        volume = 0.25,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 6, soundLevel = 80 },
        preload = true,
    })
    builder:AddLoop("fan6a_pos7", {
        sounds = "bms_objects/fans/fan6a.wav",
        volume = 0.25,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 7, soundLevel = 80 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1c.util.hallway.ctl", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("m_ambience_comp1_pos1", {
        sounds = "bms_ambience/machine_ambience/m_ambience_comp1.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("m_ambience_comp1a_pos2", {
        sounds = "bms_ambience/machine_ambience/m_ambience_comp1a.wav",
        volume = 0.6,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 65 },
        preload = true,
    })
    builder:AddLoop("fan2_pos3", {
        sounds = "bms_objects/fans/fan2.wav",
        volume = 0.3,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 3, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("fan8_pos4", {
        sounds = "bms_objects/fans/fan8.wav",
        volume = 0.1,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 4, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("m_ambience_comp2_pos5", {
        sounds = "bms_ambience/machine_ambience/m_ambience_comp2.wav",
        volume = 0.35,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 5, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("m_ambience_comp2a_pos6", {
        sounds = "bms_ambience/machine_ambience/m_ambience_comp2a.wav",
        volume = 0.4,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 6, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("m_ambience_electrichum1_pos7", {
        sounds = "bms_ambience/machine_ambience/m_ambience_electrichum1.wav",
        volume = 0.15,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 7, soundLevel = 65 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1c.hallway", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:2")
    builder:AddSubScape("c1a1c.hallway.base")
end)

ax.scapes:Register("c1a1c.hallway1", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:3")
    builder:AddSubScape("c1a1c.hallway1.base")
    builder:AddSubScape("c1a1c.hallway1.util_pos0-2")
    builder:AddSubScape("c1a1c.hallway1.util_pos3-4", {
        volumeMultiplier = 0.65,
    })
    builder:AddSubScape("c1a1c.mt1.util_pos3_6_7", {
        volumeMultiplier = 0.4,
    })
    builder:AddSubScape("c1a1.util_indoorboom1", {
        volumeMultiplier = 0.6,
    })
    builder:AddSubScape("c1a1.util_metalcreak1", {
        volumeMultiplier = 0.4,
    })
end)

ax.scapes:Register("c1a1c.frozenlab1", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:2")
    builder:AddSubScape("c1a1c.frozenlab1.base")
    builder:AddSubScape("c1a1c.hallway1.util_pos0-2")
    builder:AddSubScape("c1a1c.hallway1.util_pos3-4")
    builder:AddSubScape("c1a1c.mt1.util_pos3_6_7", {
        volumeMultiplier = 0.2,
    })
    builder:AddSubScape("c1a1.util_indoorboom1", {
        volumeMultiplier = 0.3,
    })
    builder:AddSubScape("c1a1.util_metalcreak1", {
        volumeMultiplier = 0.3,
    })
end)

ax.scapes:Register("c1a1c.maintenance1", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:17")
    builder:AddSubScape("c1a1c.hallway1.util_pos0-2", {
        volumeMultiplier = 0.55,
    })
    builder:AddSubScape("c1a1c.mt1.util_pos3_6_7")
    builder:AddSubScape("c1a1.util_indoorboom1", {
        volumeMultiplier = 0.2,
    })
    builder:AddSubScape("c1a1.util_metalcreak1", {
        volumeMultiplier = 0.2,
    })
    builder:AddLoop("r_ambience_disaster_rumble6", {
        sounds = "BMS_ambience/room_ambience/r_ambience_disaster_rumble6.wav",
        volume = 0.2,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("r_ambience_med8", {
        sounds = "BMS_ambience/room_ambience/r_ambience_med8.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1c.shaft.ele", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:17")
    builder:AddSubScape("c1a1c.elevatorshaft.util_pos3_6_7")
    builder:AddSubScape("c1a1.util_indoorboom1", {
        volumeMultiplier = 0.1,
    })
    builder:AddSubScape("c1a1.util_metalcreak1", {
        volumeMultiplier = 0.7,
    })
    builder:AddLoop("r_ambience_eleshaft1", {
        sounds = "bms_ambience/room_ambience/r_ambience_eleshaft1.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1c.warehouse1", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:2")
    builder:AddSubScape("c1a1c.warehouse.base")
    builder:AddSubScape("c1a1c.warehouse.util_pos4-7")
    builder:AddSubScape("c1a1.util_indoorboom1", {
        volumeMultiplier = 0.1,
    })
    builder:AddSubScape("c1a1.util_metalcreak1", {
        volumeMultiplier = 0.1,
    })
end)

ax.scapes:Register("c1a1c.hallway2", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:2")
    builder:AddSubScape("c1a1c.util.hallway2")
    builder:AddSubScape("c1a1.util_indoorboom1", {
        volumeMultiplier = 0.1,
    })
    builder:AddLoop("r_ambience_large2", {
        sounds = "BMS_ambience/room_ambience/r_ambience_large2.wav",
        volume = 0.4,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("r_ambience_med9", {
        sounds = "BMS_ambience/room_ambience/r_ambience_med9.wav",
        volume = 0.3,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1c.hallway2.maintenancetunnel", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:2")
    builder:AddSubScape("c1a1c.util.hallway2")
    builder:AddSubScape("c1a1.util_indoorboom1", {
        volumeMultiplier = 0.1,
    })
    builder:AddLoop("r_ambience_large2", {
        sounds = "BMS_ambience/room_ambience/r_ambience_large2.wav",
        volume = 0.2,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("r_ambience_med9", {
        sounds = "BMS_ambience/room_ambience/r_ambience_med9.wav",
        volume = 0.1,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("r_ambience_med14", {
        sounds = "BMS_ambience/room_ambience/r_ambience_med14.wav",
        volume = 0.3,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1c.frozenlab2", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:2")
    builder:AddSubScape("c1a1c.util.hallway2")
    builder:AddSubScape("c1a1.util_indoorboom1", {
        volumeMultiplier = 0.1,
    })
    builder:AddLoop("r_ambience_med14", {
        sounds = "BMS_ambience/room_ambience/r_ambience_med14.wav",
        volume = 0.7,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("r_ambience_large2", {
        sounds = "BMS_ambience/room_ambience/r_ambience_large2.wav",
        volume = 0.2,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1c.frozenlab3", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:2")
    builder:AddSubScape("c1a1.util_indoorboom1", {
        volumeMultiplier = 0.1,
    })
    builder:AddSubScape("c1a1c.util.hallway2", {
        volumeMultiplier = 0.5,
    })
    builder:AddLoop("r_ambience_med14", {
        sounds = "BMS_ambience/room_ambience/r_ambience_med14.wav",
        volume = 0.7,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("r_ambience_large2", {
        sounds = "BMS_ambience/room_ambience/r_ambience_large2.wav",
        volume = 0.2,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("fan8_pos0", {
        sounds = "bms_objects/fans/fan8.wav",
        volume = 0.8,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 65 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1c.frozenlab4", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddSubScape("c1a1.util_indoorboom1", {
        volumeMultiplier = 0.08,
    })
    builder:AddLoop("r_ambience_med14", {
        sounds = "BMS_ambience/room_ambience/r_ambience_med14.wav",
        volume = 0.7,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("r_ambience_large2", {
        sounds = "BMS_ambience/room_ambience/r_ambience_large2.wav",
        volume = 0.2,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1c.hallway.ctl", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:2")
    builder:AddSubScape("c1a1.util_indoorboom1", {
        volumeMultiplier = 0.1,
    })
    builder:AddSubScape("c1a1c.util.hallway.ctl")
    builder:AddLoop("r_ambience_large2", {
        sounds = "BMS_ambience/room_ambience/r_ambience_large2.wav",
        volume = 0.4,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("r_ambience_med9", {
        sounds = "BMS_ambience/room_ambience/r_ambience_med9.wav",
        volume = 0.3,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1c.frozenlab.ctl", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddSubScape("c1a1.util_indoorboom1", {
        volumeMultiplier = 0.1,
    })
    builder:AddSubScape("c1a1c.util.hallway.ctl")
    builder:AddLoop("r_ambience_med14", {
        sounds = "BMS_ambience/room_ambience/r_ambience_med14.wav",
        volume = 0.7,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("r_ambience_large2", {
        sounds = "BMS_ambience/room_ambience/r_ambience_large2.wav",
        volume = 0.2,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1c.frozenlab.ctl2", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddSubScape("c1a1.util_indoorboom1", {
        volumeMultiplier = 0.1,
    })
    builder:AddSubScape("c1a1c.util.hallway.ctl")
    builder:AddLoop("r_ambience_med14", {
        sounds = "BMS_ambience/room_ambience/r_ambience_med14.wav",
        volume = 0.7,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("r_ambience_large2", {
        sounds = "BMS_ambience/room_ambience/r_ambience_large2.wav",
        volume = 0.2,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1c.hallway.ctu", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:2")
    builder:AddSubScape("c1a1.util_indoorboom1", {
        volumeMultiplier = 0.08,
    })
    builder:AddLoop("r_ambience_large2", {
        sounds = "BMS_ambience/room_ambience/r_ambience_large2.wav",
        volume = 0.4,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("r_ambience_med9", {
        sounds = "BMS_ambience/room_ambience/r_ambience_med9.wav",
        volume = 0.3,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipe2a_pos0", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipe2a.wav",
        volume = 0.2,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipe4_pos1", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipe4.wav",
        volume = 0.2,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("m_ambience_electrichum1_pos2", {
        sounds = "bms_ambience/machine_ambience/m_ambience_electrichum1.wav",
        volume = 0.15,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 65 },
        preload = true,
    })
    builder:AddLoop("m_ambience_watercontainer_pos4", {
        sounds = "BMS_ambience/machine_ambience/m_ambience_watercontainer.wav",
        volume = 0.2,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 4, soundLevel = 80 },
        preload = true,
    })
    builder:AddLoop("m_ambience_watercontainer2_pos6", {
        sounds = "BMS_ambience/machine_ambience/m_ambience_watercontainer2.wav",
        volume = 0.2,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 6, soundLevel = 80 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1c.secoffice.ctu", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:2")
    builder:AddLoop("r_ambience_large2", {
        sounds = "BMS_ambience/room_ambience/r_ambience_large2.wav",
        volume = 0.4,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("r_ambience_med9", {
        sounds = "BMS_ambience/room_ambience/r_ambience_med9.wav",
        volume = 0.3,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_electrichum1a_pos0", {
        sounds = "bms_ambience/machine_ambience/m_ambience_electrichum1a.wav",
        volume = 0.15,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 60 },
        preload = true,
    })
    builder:AddLoop("m_ambience_comp1_pos7", {
        sounds = "bms_ambience/machine_ambience/m_ambience_comp1.wav",
        volume = 0.4,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 7, soundLevel = 70 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1c.hallway3", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:2")
    builder:AddSubScape("c1a1c.util.hallway3")
    builder:AddSubScape("c1a1c.util.hallway4", {
        volumeMultiplier = 0.8,
    })
    builder:AddLoop("r_ambience_large2", {
        sounds = "BMS_ambience/room_ambience/r_ambience_large2.wav",
        volume = 0.4,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("r_ambience_med9", {
        sounds = "BMS_ambience/room_ambience/r_ambience_med9.wav",
        volume = 0.3,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1c.hallway4.dumpster", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:2")
    builder:AddSubScape("c1a1c.util.hallway3", {
        volumeMultiplier = 0.5,
    })
    builder:AddSubScape("c1a1c.util.hallway4")
    builder:AddLoop("r_ambience_large2", {
        sounds = "BMS_ambience/room_ambience/r_ambience_large2.wav",
        volume = 0.4,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("r_ambience_med9", {
        sounds = "BMS_ambience/room_ambience/r_ambience_med9.wav",
        volume = 0.3,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1c.hallway4.closet", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:2")
    builder:AddSubScape("c1a1c.util.hallway4.closet")
    builder:AddLoop("r_ambience_large2", {
        sounds = "BMS_ambience/room_ambience/r_ambience_large2.wav",
        volume = 0.4,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("r_ambience_med9", {
        sounds = "BMS_ambience/room_ambience/r_ambience_med9.wav",
        volume = 0.3,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1c.util.hallway4.closet", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:AddLoop("m_ambience_electrichum1_pos4", {
        sounds = "bms_ambience/machine_ambience/m_ambience_electrichum1.wav",
        volume = 0.2,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 4, soundLevel = 60 },
        preload = true,
    })
    builder:AddLoop("fan6_pos6", {
        sounds = "bms_objects/fans/fan6.wav",
        volume = 0.25,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 6, soundLevel = 80 },
        preload = true,
    })
    builder:AddLoop("fan6a_pos7", {
        sounds = "bms_objects/fans/fan6a.wav",
        volume = 0.25,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 7, soundLevel = 80 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1c.sewers", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:1")
    builder:AddSubScape("c1a1c.util.hallway4", {
        volumeMultiplier = 0.2,
    })
    builder:AddLoop("r_ambience_water3", {
        sounds = "BMS_ambience/room_ambience/r_ambience_water3.wav",
        volume = 0.6,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("r_ambience_large2", {
        sounds = "BMS_ambience/room_ambience/r_ambience_large2.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("r_ambience_water_room_ST", {
        sounds = "BMS_ambience/room_ambience/r_ambience_water_room_ST.wav",
        volume = 0.4,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1c.hallway5.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:AddLoop("r_ambience_large2", {
        sounds = "BMS_ambience/room_ambience/r_ambience_large2.wav",
        volume = 0.4,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("r_ambience_med9", {
        sounds = "BMS_ambience/room_ambience/r_ambience_med9.wav",
        volume = 0.3,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1c.hallway5.endmap", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:2")
    builder:AddSubScape("c1a1c.hallway5.base")
    builder:AddSubScape("c1a1c.util.hallway4", {
        volumeMultiplier = 0.6,
    })
    builder:AddLoop("m_ambience_pipe3_pos0", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipe3.wav",
        volume = 0.4,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("waterleak_loop1_pos1", {
        sounds = "ambient/levels/canals/waterleak_loop1.wav",
        volume = 0.2,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipe4_pos2", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipe4.wav",
        volume = 0.3,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("waterleak_loop1_pos3", {
        sounds = "ambient/levels/canals/waterleak_loop1.wav",
        volume = 0.2,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 3, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipe5_pos7", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipe5.wav",
        volume = 0.3,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 7, soundLevel = 70 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1d.shaft.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("r_ambience_large4", {
        sounds = "bms_ambience/room_ambience/r_ambience_large4.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("r_ambience_pipes1", {
        sounds = "bms_ambience/room_ambience/r_ambience_pipes1.wav",
        volume = 0.15,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1d.securityoffice.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("r_ambience_large2", {
        sounds = "bms_ambience/room_ambience/r_ambience_large2.wav",
        volume = 0.4,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("r_ambience_med9", {
        sounds = "bms_ambience/room_ambience/r_ambience_med9.wav",
        volume = 0.3,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1d.storage.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("r_ambience_large4", {
        sounds = "bms_ambience/room_ambience/r_ambience_large4.wav",
        volume = 0.4,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("r_ambience_large2", {
        sounds = "bms_ambience/room_ambience/r_ambience_large2.wav",
        volume = 0.2,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1d.hallway.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("r_ambience_large7", {
        sounds = "bms_ambience/room_ambience/r_ambience_large7.wav",
        volume = 0.8,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1c.hallway5.d_version1", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:2")
    builder:AddSubScape("c1a1c.hallway5.base")
    builder:AddLoop("m_ambience_pipe4_pos2", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipe4.wav",
        volume = 0.3,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("waterleak_loop1_pos3", {
        sounds = "ambient/levels/canals/waterleak_loop1.wav",
        volume = 0.2,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 3, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipe5_pos7", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipe5.wav",
        volume = 0.3,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 7, soundLevel = 70 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1c.hallway5.d_version2", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:2")
    builder:AddSubScape("c1a1c.hallway5.base")
    builder:AddSubScape("c1a1d.shaft.base", {
        volumeMultiplier = 0.3,
    })
    builder:AddLoop("fan6_pos0", {
        sounds = "bms_objects/fans/fan6.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipeflow1_pos1", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipeflow1.wav",
        volume = 0.2,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 80 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipe4_pos2", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipe4.wav",
        volume = 0.3,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("waterleak_loop1_pos3", {
        sounds = "ambient/levels/canals/waterleak_loop1.wav",
        volume = 0.2,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 3, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipe5_pos7", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipe5.wav",
        volume = 0.3,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 7, soundLevel = 70 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1d.shaft1.pre", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:4")
    builder:AddSubScape("c1a1d.shaft.base")
    builder:AddSubScape("c1a1d.shaft1.pre_util_pos")
end)

ax.scapes:Register("c1a1d.shaft1.pre_util_pos", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("fan6_pos0", {
        sounds = "bms_objects/fans/fan6.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipeflow1_pos1", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipeflow1.wav",
        volume = 0.2,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipe3_pos2", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipe3.wav",
        volume = 0.4,
        pitch = 90.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipe2a_pos3", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipe2a.wav",
        volume = 0.25,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 3, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipe2b_pos4", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipe2b.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 4, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipe1_pos5", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipe1.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 5, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipe1a_pos6", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipe1a.wav",
        volume = 0.4,
        pitch = 110.0,
        spatial = { mode = "positional", positionKey = 6, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipe5_pos7", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipe5.wav",
        volume = 0.3,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 7, soundLevel = 70 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1d.vent", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:2")
    builder:AddSubScape("c1a1d.shaft1.pre_util_pos", {
        volumeMultiplier = 0.7,
    })
    builder:AddLoop("r_ambience_vent1", {
        sounds = "BMS_ambience/room_ambience/r_ambience_vent1.wav",
        volume = 0.6,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("r_ambience_pipes1", {
        sounds = "BMS_ambience/room_ambience/r_ambience_pipes1.wav",
        volume = 0.03,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1d.vent2", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:2")
    builder:AddLoop("r_ambience_vent1", {
        sounds = "BMS_ambience/room_ambience/r_ambience_vent1.wav",
        volume = 0.6,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("fan6_pos0", {
        sounds = "bms_objects/fans/fan6.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("fan8_pos1", {
        sounds = "bms_objects/fans/fan8.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1d.securityoffice1", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:2")
    builder:AddSubScape("c1a1d.securityoffice.base")
    builder:AddLoop("r_ambience_pipes1", {
        sounds = "bms_ambience/room_ambience/r_ambience_pipes1.wav",
        volume = 0.07,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("fan6_pos0", {
        sounds = "bms_objects/fans/fan6.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_comp3_pos1", {
        sounds = "bms_ambience/machine_ambience/m_ambience_comp3.wav",
        volume = 0.8,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1d.shaft1", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:4")
    builder:AddSubScape("c1a1d.storage_a1.util_pos")
    builder:AddLoop("r_ambience_large4", {
        sounds = "BMS_ambience/room_ambience/r_ambience_large4.wav",
        volume = 0.6,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("r_ambience_pipes1", {
        sounds = "BMS_ambience/room_ambience/r_ambience_pipes1.wav",
        volume = 0.11,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1d.storage_a1", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:17")
    builder:AddSubScape("c1a1d.storage.base")
    builder:AddSubScape("c1a1d.storage_a1.util_pos")
end)

ax.scapes:Register("c1a1d.storage_a1.util_pos", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("electric_machine_pos0", {
        sounds = "ambient/machines/electric_machine.wav",
        volume = 0.4,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipeflow1_pos1", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipeflow1.wav",
        volume = 0.3,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("r_ambience_water15_pos2", {
        sounds = "bms_ambience/room_ambience/r_ambience_water15.wav",
        volume = 0.33,
        pitch = 110.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 80 },
        preload = true,
    })
    builder:AddLoop("waterleak_loop1_pos3", {
        sounds = "ambient/levels/canals/waterleak_loop1.wav",
        volume = 0.8,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 3, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("waterleak_loop1_NULL_pos4", {
        sounds = "ambient/levels/canals/waterleak_loop1_NULL.wav",
        volume = 0.8,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 4, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipeflow2_pos5", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipeflow2.wav",
        volume = 0.3,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 5, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipe3_pos6", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipe3.wav",
        volume = 0.3,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 6, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipeflow2a_pos7", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipeflow2a.wav",
        volume = 0.3,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 7, soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1d.securityoffice2", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:2")
    builder:AddSubScape("c1a1d.securityoffice.base")
    builder:AddLoop("electric_machine_pos0", {
        sounds = "ambient/machines/electric_machine.wav",
        volume = 0.04,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_comp2_pos1", {
        sounds = "bms_ambience/machine_ambience/m_ambience_comp2.wav",
        volume = 0.3,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_comp2a_pos2", {
        sounds = "bms_ambience/machine_ambience/m_ambience_comp2a.wav",
        volume = 0.3,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1d.hallway1", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:4")
    builder:AddSubScape("c1a1d.hallway.base")
    builder:AddSubScape("c1a1d.storage_a1.util_pos")
end)

ax.scapes:Register("c1a1d.canal1", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:25")
    builder:AddSubScape("c1a1.util_indamb", {
        volumeMultiplier = 0.2,
    })
    builder:AddSubScape("c1a1d.hallway2.util_pos")
    builder:AddLoop("r_ambience_large6", {
        sounds = "BMS_ambience/room_ambience/r_ambience_large6.wav",
        volume = 0.9,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1d.hallway2", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:4")
    builder:AddSubScape("c1a1d.hallway.base")
    builder:AddSubScape("c1a1d.hallway2.util_pos")
end)

ax.scapes:Register("c1a1d.hallway2.util_pos", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("hum1_pos0", {
        sounds = "bms_objects/hum/hum1.wav",
        volume = 1.0,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipeflow1_pos1", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipeflow1.wav",
        volume = 0.25,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipeflow1a_pos2", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipeflow1a.wav",
        volume = 0.25,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("m_ambience_electrichum1_pos3", {
        sounds = "bms_ambience/machine_ambience/m_ambience_electrichum1.wav",
        volume = 0.2,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 3, soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1d.corridor.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("r_ambience_pipes1", {
        sounds = "BMS_ambience/room_ambience/r_ambience_pipes1.wav",
        volume = 0.1,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("r_ambience_med4", {
        sounds = "BMS_ambience/room_ambience/r_ambience_med4.wav",
        volume = 1.0,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1e.corridor2.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("r_ambience_pipes1", {
        sounds = "BMS_ambience/room_ambience/r_ambience_pipes1.wav",
        volume = 0.08,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("r_ambience_med4", {
        sounds = "BMS_ambience/room_ambience/r_ambience_med4.wav",
        volume = 1.0,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1e.hallway.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("r_ambience_large7", {
        sounds = "BMS_ambience/room_ambience/r_ambience_large7.wav",
        volume = 0.8,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1e.canal3.controlroom.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("r_ambience_med6", {
        sounds = "BMS_ambience/room_ambience/r_ambience_med6.wav",
        volume = 0.7,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("r_ambience_large9", {
        sounds = "BMS_ambience/room_ambience/r_ambience_large9.wav",
        volume = 0.4,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("r_ambience_industrial1", {
        sounds = "BMS_ambience/room_ambience/r_ambience_industrial1.wav",
        volume = 0.1,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1e.storage.base", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:4")
    builder:AddLoop("r_ambience_large7", {
        sounds = "BMS_ambience/room_ambience/r_ambience_large7.wav",
        volume = 0.9,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("r_ambience_med14", {
        sounds = "BMS_ambience/room_ambience/r_ambience_med14.wav",
        volume = 0.2,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1e.canal2", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:4")
    builder:AddSubScape("c1a1.util_indamb", {
        volumeMultiplier = 0.4,
    })
    builder:AddLoop("r_ambience_large6", {
        sounds = "BMS_ambience/room_ambience/r_ambience_large6.wav",
        volume = 0.9,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("r_ambience_med10", {
        sounds = "BMS_ambience/room_ambience/r_ambience_med10.wav",
        volume = 0.4,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1e.canal2a", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:4")
    builder:AddSubScape("c1a1.util_indamb", {
        volumeMultiplier = 0.4,
    })
    builder:AddSubScape("c1a1e.canal2a.util_pos")
    builder:AddSubScape("c1a1e.corridor2.util_pos")
    builder:AddLoop("r_ambience_large6", {
        sounds = "BMS_ambience/room_ambience/r_ambience_large6.wav",
        volume = 0.9,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("r_ambience_med10", {
        sounds = "BMS_ambience/room_ambience/r_ambience_med10.wav",
        volume = 0.4,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1e.canal2a.util_pos", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:4")
    builder:AddLoop("m_ambience_pipeflow2_pos7", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipeflow2.wav",
        volume = 0.15,
        pitch = 150.0,
        spatial = { mode = "positional", positionKey = 7, soundLevel = 70 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1e.corridor2", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:17")
    builder:AddSubScape("c1a1e.corridor2.base")
    builder:AddSubScape("c1a1e.canal2a.util_pos")
    builder:AddSubScape("c1a1e.corridor2.util_pos")
    builder:AddLoop("r_ambience_large6", {
        sounds = "BMS_ambience/room_ambience/r_ambience_large6.wav",
        volume = 0.4,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1e.corridor2.util_pos", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:4")
    builder:AddLoop("hum1_pos0", {
        sounds = "bms_objects/hum/hum1.wav",
        volume = 0.6,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipeflow1_pos1", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipeflow1.wav",
        volume = 0.2,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipe3_pos2", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipe3.wav",
        volume = 0.15,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 70 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1e.canal3", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:4")
    builder:AddSubScape("c1a1.util_indamb", {
        volumeMultiplier = 0.4,
    })
    builder:AddSubScape("c1a1e.canal3.util_pos")
    builder:AddLoop("r_ambience_large9", {
        sounds = "BMS_ambience/room_ambience/r_ambience_large9.wav",
        volume = 1.0,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("r_ambience_industrial1", {
        sounds = "BMS_ambience/room_ambience/r_ambience_industrial1.wav",
        volume = 0.4,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1e.canal3.util_pos", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("hum1b_pos6", {
        sounds = "bms_objects/hum/hum1b.wav",
        volume = 1.0,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 6, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipe4_pos7", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipe4.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 7, soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1e.canal3.controlroom", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:7")
    builder:AddSubScape("c1a1e.c3.ctrlroom.utilpos")
    builder:AddLoop("r_ambience_med6", {
        sounds = "BMS_ambience/room_ambience/r_ambience_med6.wav",
        volume = 0.7,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("r_ambience_large9", {
        sounds = "BMS_ambience/room_ambience/r_ambience_large9.wav",
        volume = 0.4,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("r_ambience_industrial1", {
        sounds = "BMS_ambience/room_ambience/r_ambience_industrial1.wav",
        volume = 0.1,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1e.c3.ctrlroom.utilpos", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("m_ambience_comp2_pos0", {
        sounds = "bms_ambience/machine_ambience/m_ambience_comp2.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_comp1_pos1", {
        sounds = "bms_ambience/machine_ambience/m_ambience_comp1.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_comp2_pos2", {
        sounds = "bms_ambience/machine_ambience/m_ambience_comp2.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1e.corridor1", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:17")
    builder:AddSubScape("c1a1d.corridor.base")
end)

ax.scapes:Register("c1a1e.corridor3", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:17")
    builder:AddSubScape("c1a1d.corridor.base")
    builder:AddSubScape("c1a1e.corridor3.util_pos")
end)

ax.scapes:Register("c1a1e.corridor3.util_pos", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("m_ambience_pipeflow2_pos0", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipeflow2.wav",
        volume = 0.25,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipeflow2a_pos1", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipeflow2a.wav",
        volume = 0.25,
        pitch = 115.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipeflow1_pos2", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipeflow1.wav",
        volume = 0.25,
        pitch = 50.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipeflow1a_pos3", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipeflow1a.wav",
        volume = 0.25,
        pitch = 50.0,
        spatial = { mode = "positional", positionKey = 3, soundLevel = 70 },
        preload = true,
    })
    builder:AddLoop("m_ambience_electrichum1_pos4", {
        sounds = "bms_ambience/machine_ambience/m_ambience_electrichum1.wav",
        volume = 0.2,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 4, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_electrichum1a_pos5", {
        sounds = "bms_ambience/machine_ambience/m_ambience_electrichum1a.wav",
        volume = 0.2,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 5, soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1e.corridor3.mod01", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:17")
    builder:AddLoop("r_ambience_med4", {
        sounds = "bms_ambience/room_ambience/r_ambience_med4.wav",
        volume = 1.0,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("r_ambience_pipes1", {
        sounds = "bms_ambience/room_ambience/r_ambience_pipes1.wav",
        volume = 0.05,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1e.corridor3_lower", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:17")
    builder:AddSubScape("c1a1d.corridor.base")
    builder:AddSubScape("c1a1e.corridor3l.util_pos")
end)

ax.scapes:Register("c1a1e.corridor3_basic", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:17")
    builder:AddSubScape("c1a1d.corridor.base")
end)

ax.scapes:Register("c1a1e.corridor3l.util_pos", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("m_ambience_pipeflow2a_pos0", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipeflow2a.wav",
        volume = 0.25,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipeflow1_pos1", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipeflow1.wav",
        volume = 0.55,
        pitch = 115.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipeflow2_pos2", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipeflow2.wav",
        volume = 0.25,
        pitch = 90.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1e.corridor4", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:17")
    builder:AddSubScape("c1a1d.corridor.base")
    builder:AddSubScape("c1a1e.corridor4.util_pos")
    builder:AddLoop("r_ambience_large9", {
        sounds = "BMS_ambience/room_ambience/r_ambience_large9.wav",
        volume = 0.3,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("r_ambience_industrial1", {
        sounds = "BMS_ambience/room_ambience/r_ambience_industrial1.wav",
        volume = 0.1,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1e.corridor4.util_pos", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("m_ambience_pipe2_pos0", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipe2.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipeflow1_pos1", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipeflow1.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipe3_pos2", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipe3.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1e.corridor5", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:17")
    builder:AddSubScape("c1a1d.corridor.base")
    builder:AddSubScape("c1a1e.corridor5.util_pos")
    builder:AddLoop("r_ambience_large9", {
        sounds = "BMS_ambience/room_ambience/r_ambience_large9.wav",
        volume = 0.1,
        pitch = 100.0,
        spatial = { mode = "ambient", soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1e.corridor5.util_pos", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("m_ambience_pipe1_pos0", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipe1.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipe3a_pos1", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipe3a.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipeflow1a_pos2", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipeflow1a.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipe5_pos3", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipe5.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 3, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipeflow1_pos6", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipeflow1.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 6, soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1e.hallway.final", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:4")
    builder:AddSubScape("c1a1e.hallway.base")
    builder:AddSubScape("c1a1e.hallway.final_utilpos")
end)

ax.scapes:Register("c1a1e.hallway.final_utilpos", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("m_ambience_pipe3_pos7", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipe3.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 7, soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("c1a1e.storagearea.B2", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:17")
    builder:AddSubScape("c1a1e.storage.base")
    builder:AddSubScape("c1a1e.hallway.final_utilpos")
    builder:AddSubScape("c1a1e.storagearea.B2_utilpos")
end)

ax.scapes:Register("c1a1e.storagearea.B2_utilpos", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
    builder:SetMixerProfile("dsp:0")
    builder:AddLoop("m_ambience_electrichum1_pos0", {
        sounds = "bms_ambience/machine_ambience/m_ambience_electrichum1.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 0, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_electrichum1a_pos1", {
        sounds = "bms_ambience/machine_ambience/m_ambience_electrichum1a.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 1, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipeflow1a_pos2", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipeflow1a.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 2, soundLevel = 75 },
        preload = true,
    })
    builder:AddLoop("m_ambience_pipeflow2a_pos3", {
        sounds = "bms_ambience/machine_ambience/m_ambience_pipeflow2a.wav",
        volume = 0.5,
        pitch = 100.0,
        spatial = { mode = "positional", positionKey = 3, soundLevel = 75 },
        preload = true,
    })
end)

ax.scapes:Register("soundscapes_c1a1.ArmClose", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
end)

ax.scapes:Register("soundscapes_c1a1.ArmOpen", function(builder)
    builder:SetMixTag("c0a0")
    builder:SetPriority(30)
    builder:SetFade(1.0, 1.0)
    builder:SetPauseLegacyAmbient(true)
end)
